type Dictionary = Record<string, string>;

const nb: Dictionary = {
  'access.saved':'Tilgangsinnstillingene er lagret.','access.deletePrefix':'Slette invitasjonskoden ','access.deleteSuffix':'?','access.copied':'Kopiert.','access.title':'Tilgang og medlemskap','access.subtitle':'Bestem hvem som kan se appen, og hvordan brukere blir medlemmer.','access.appAccess':'Tilgang til app','access.publicTitle':'Offentlig','access.publicBody':'Nyheter, aktiviteter og kontakt kan ses uten innlogging.','access.mixedTitle':'Offentlig med private områder','access.mixedBody':'Noe er offentlig, mens internt innhold krever innlogging.','access.authTitle':'Kun for innloggede brukere','access.authBody':'Brukeren må logge inn før innhold vises.','access.approval':'Godkjenning av nye brukere','access.autoApproval':'Godkjennes automatisk med gyldig kode','access.manualApproval':'Må godkjennes av administrator','access.save':'Lagre tilgang','access.codes':'Invitasjonskoder','access.activeCodes':'aktive koder','access.newCode':'Ny kode','access.noCodes':'Ingen invitasjonskoder ennå.','access.used':'brukt','access.of':'av','access.expires':'utløper','access.active':'Aktiv','access.off':'Av','access.copy':'Kopier','access.disable':'Deaktiver','access.enable':'Aktiver','access.delete':'Slett','access.newCodeTitle':'Ny invitasjonskode','access.codeLabel':'Navn på koden, f.eks. Beboere','access.member':'Medlem','access.resident':'Beboer','access.volunteer':'Frivillig','access.staff':'Ansatt','access.board':'Styremedlem','access.inherit':'Bruk organisasjonens innstilling','access.automatic':'Automatisk godkjenning','access.manual':'Manuell godkjenning','access.maxUses':'Maks bruk (valgfritt)','access.cancel':'Avbryt','access.create':'Opprett kode'
};
const en: Dictionary = {
  'access.saved':'Access settings have been saved.','access.deletePrefix':'Delete invitation code ','access.deleteSuffix':'?','access.copied':'Copied.','access.title':'Access and membership','access.subtitle':'Decide who can view the app and how users become members.','access.appAccess':'App access','access.publicTitle':'Public','access.publicBody':'News, activities and contact information can be viewed without signing in.','access.mixedTitle':'Public with private areas','access.mixedBody':'Some content is public, while internal content requires sign-in.','access.authTitle':'Signed-in users only','access.authBody':'Users must sign in before content is shown.','access.approval':'Approval of new users','access.autoApproval':'Approved automatically with a valid code','access.manualApproval':'Must be approved by an administrator','access.save':'Save access','access.codes':'Invitation codes','access.activeCodes':'active codes','access.newCode':'New code','access.noCodes':'No invitation codes yet.','access.used':'used','access.of':'of','access.expires':'expires','access.active':'Active','access.off':'Off','access.copy':'Copy','access.disable':'Disable','access.enable':'Enable','access.delete':'Delete','access.newCodeTitle':'New invitation code','access.codeLabel':'Code name, for example Residents','access.member':'Member','access.resident':'Resident','access.volunteer':'Volunteer','access.staff':'Staff','access.board':'Board member','access.inherit':'Use the organization setting','access.automatic':'Automatic approval','access.manual':'Manual approval','access.maxUses':'Maximum uses (optional)','access.cancel':'Cancel','access.create':'Create code'
};
const tr: Dictionary = {
  'access.saved':'Erişim ayarları kaydedildi.','access.deletePrefix':'Davet kodunu sil: ','access.deleteSuffix':'?','access.copied':'Kopyalandı.','access.title':'Erişim ve üyelik','access.subtitle':'Uygulamayı kimlerin görebileceğini ve kullanıcıların nasıl üye olacağını belirleyin.','access.appAccess':'Uygulama erişimi','access.publicTitle':'Herkese açık','access.publicBody':'Haberler, etkinlikler ve iletişim bilgileri giriş yapmadan görülebilir.','access.mixedTitle':'Özel alanları olan herkese açık uygulama','access.mixedBody':'Bazı içerikler herkese açıktır, dahili içerikler giriş gerektirir.','access.authTitle':'Yalnızca giriş yapan kullanıcılar','access.authBody':'İçerik gösterilmeden önce kullanıcı giriş yapmalıdır.','access.approval':'Yeni kullanıcı onayı','access.autoApproval':'Geçerli kodla otomatik onay','access.manualApproval':'Yönetici onayı gerekir','access.save':'Erişimi kaydet','access.codes':'Davet kodları','access.activeCodes':'aktif kod','access.newCode':'Yeni kod','access.noCodes':'Henüz davet kodu yok.','access.used':'kullanıldı','access.of':'/','access.expires':'sona erer','access.active':'Aktif','access.off':'Kapalı','access.copy':'Kopyala','access.disable':'Devre dışı bırak','access.enable':'Etkinleştir','access.delete':'Sil','access.newCodeTitle':'Yeni davet kodu','access.codeLabel':'Kod adı, örn. Sakinler','access.member':'Üye','access.resident':'Sakin','access.volunteer':'Gönüllü','access.staff':'Çalışan','access.board':'Yönetim kurulu üyesi','access.inherit':'Kuruluş ayarını kullan','access.automatic':'Otomatik onay','access.manual':'Manuel onay','access.maxUses':'Maksimum kullanım (isteğe bağlı)','access.cancel':'İptal','access.create':'Kod oluştur'
};
const ar: Dictionary = {
  'access.saved':'تم حفظ إعدادات الوصول.','access.deletePrefix':'حذف رمز الدعوة ','access.deleteSuffix':'؟','access.copied':'تم النسخ.','access.title':'الوصول والعضوية','access.subtitle':'حدّد من يمكنه رؤية التطبيق وكيف يصبح المستخدمون أعضاء.','access.appAccess':'الوصول إلى التطبيق','access.publicTitle':'عام','access.publicBody':'يمكن عرض الأخبار والأنشطة ومعلومات الاتصال دون تسجيل الدخول.','access.mixedTitle':'عام مع مناطق خاصة','access.mixedBody':'بعض المحتوى عام، بينما يتطلب المحتوى الداخلي تسجيل الدخول.','access.authTitle':'للمستخدمين المسجلين فقط','access.authBody':'يجب تسجيل الدخول قبل عرض المحتوى.','access.approval':'الموافقة على المستخدمين الجدد','access.autoApproval':'موافقة تلقائية باستخدام رمز صالح','access.manualApproval':'تتطلب موافقة المسؤول','access.save':'حفظ الوصول','access.codes':'رموز الدعوة','access.activeCodes':'رموز نشطة','access.newCode':'رمز جديد','access.noCodes':'لا توجد رموز دعوة بعد.','access.used':'استخدم','access.of':'من','access.expires':'ينتهي','access.active':'نشط','access.off':'متوقف','access.copy':'نسخ','access.disable':'تعطيل','access.enable':'تفعيل','access.delete':'حذف','access.newCodeTitle':'رمز دعوة جديد','access.codeLabel':'اسم الرمز، مثلاً السكان','access.member':'عضو','access.resident':'ساكن','access.volunteer':'متطوع','access.staff':'موظف','access.board':'عضو مجلس الإدارة','access.inherit':'استخدام إعداد المؤسسة','access.automatic':'موافقة تلقائية','access.manual':'موافقة يدوية','access.maxUses':'الحد الأقصى للاستخدام (اختياري)','access.cancel':'إلغاء','access.create':'إنشاء الرمز'
};
const ur: Dictionary = {
  'access.saved':'رسائی کی ترتیبات محفوظ ہو گئیں۔','access.deletePrefix':'دعوتی کوڈ حذف کریں ','access.deleteSuffix':'؟','access.copied':'کاپی ہو گیا۔','access.title':'رسائی اور رکنیت','access.subtitle':'طے کریں کہ ایپ کون دیکھ سکتا ہے اور صارف رکن کیسے بنتے ہیں۔','access.appAccess':'ایپ تک رسائی','access.publicTitle':'عوامی','access.publicBody':'خبریں، سرگرمیاں اور رابطہ معلومات بغیر لاگ اِن دیکھی جا سکتی ہیں۔','access.mixedTitle':'نجی حصوں کے ساتھ عوامی','access.mixedBody':'کچھ مواد عوامی ہے جبکہ اندرونی مواد کے لیے لاگ اِن ضروری ہے۔','access.authTitle':'صرف لاگ اِن صارفین','access.authBody':'مواد دکھانے سے پہلے صارف کو لاگ اِن کرنا ہوگا۔','access.approval':'نئے صارفین کی منظوری','access.autoApproval':'درست کوڈ کے ساتھ خودکار منظوری','access.manualApproval':'ایڈمن کی منظوری ضروری ہے','access.save':'رسائی محفوظ کریں','access.codes':'دعوتی کوڈز','access.activeCodes':'فعال کوڈز','access.newCode':'نیا کوڈ','access.noCodes':'ابھی کوئی دعوتی کوڈ نہیں۔','access.used':'استعمال','access.of':'میں سے','access.expires':'اختتام','access.active':'فعال','access.off':'بند','access.copy':'کاپی','access.disable':'غیر فعال کریں','access.enable':'فعال کریں','access.delete':'حذف','access.newCodeTitle':'نیا دعوتی کوڈ','access.codeLabel':'کوڈ کا نام، مثلاً رہائشی','access.member':'رکن','access.resident':'رہائشی','access.volunteer':'رضاکار','access.staff':'عملہ','access.board':'بورڈ رکن','access.inherit':'تنظیم کی ترتیب استعمال کریں','access.automatic':'خودکار منظوری','access.manual':'دستی منظوری','access.maxUses':'زیادہ سے زیادہ استعمال (اختیاری)','access.cancel':'منسوخ','access.create':'کوڈ بنائیں'
};

const dictionaries: Record<string, Dictionary> = { nb, en, tr, ar, ur };
export function getAccessTranslation(language: string, key: string) {
  return dictionaries[language]?.[key] || en[key] || nb[key] || key;
}
