type Dictionary = Record<string, string>;

const nb: Dictionary = {
  'groups.loadMembersFailed':'Kunne ikke hente medlemmer.','groups.deletePrefix':'Slette gruppen «','groups.deleteSuffix':'»?','groups.title':'Brukergrupper','groups.subtitle':'Opprett grupper og velg hvilke medlemmer som tilhører dem.','groups.new':'Ny gruppe','groups.empty':'Ingen grupper er opprettet ennå.','groups.members':'Medlemmer','groups.edit':'Rediger gruppe','groups.name':'Gruppenavn','groups.description':'Beskrivelse (valgfritt)','groups.save':'Lagre gruppe','groups.manageMembers':'Administrer medlemmer','groups.searchMember':'Søk medlem','groups.noUsers':'Ingen appbrukere er registrert i organisasjonen ennå.','groups.userPrefix':'Bruker ','groups.pending':'Venter på godkjenning','groups.cancel':'Avbryt','groups.saveSelectedPrefix':'Lagre (','groups.saveSelectedSuffix':')','groups.close':'Lukk','groups.roleMember':'Medlem','groups.roleResident':'Beboer','groups.roleVolunteer':'Frivillig','groups.roleStaff':'Ansatt','groups.roleBoard':'Styremedlem','groups.roleAdmin':'Administrator',
  'visibility.public':'Offentlig','visibility.authenticated':'Alle innloggede','visibility.members':'Kun medlemmer','visibility.staff':'Kun ansatte og styret','visibility.admins':'Kun administratorer','visibility.groups':'Valgte grupper','visibility.untitled':'Uten tittel','visibility.title':'Tilgang per innhold','visibility.subtitle':'Bestem hvem som kan se hver nyhet og aktivitet.','visibility.empty':'Ingen nyheter eller aktiviteter er opprettet.','visibility.news':'Nyhet','visibility.activity':'Aktivitet','visibility.chooseGroups':'Velg grupper','visibility.createGroupFirst':'Opprett en gruppe først.'
};
const en: Dictionary = {
  'groups.loadMembersFailed':'Members could not be loaded.','groups.deletePrefix':'Delete the group “','groups.deleteSuffix':'”?','groups.title':'User groups','groups.subtitle':'Create groups and choose which members belong to them.','groups.new':'New group','groups.empty':'No groups have been created yet.','groups.members':'Members','groups.edit':'Edit group','groups.name':'Group name','groups.description':'Description (optional)','groups.save':'Save group','groups.manageMembers':'Manage members','groups.searchMember':'Search member','groups.noUsers':'No app users are registered in the organization yet.','groups.userPrefix':'User ','groups.pending':'Awaiting approval','groups.cancel':'Cancel','groups.saveSelectedPrefix':'Save (','groups.saveSelectedSuffix':')','groups.close':'Close','groups.roleMember':'Member','groups.roleResident':'Resident','groups.roleVolunteer':'Volunteer','groups.roleStaff':'Staff','groups.roleBoard':'Board member','groups.roleAdmin':'Administrator',
  'visibility.public':'Public','visibility.authenticated':'All signed-in users','visibility.members':'Members only','visibility.staff':'Staff and board only','visibility.admins':'Administrators only','visibility.groups':'Selected groups','visibility.untitled':'Untitled','visibility.title':'Access per content item','visibility.subtitle':'Decide who can view each news item and activity.','visibility.empty':'No news items or activities have been created.','visibility.news':'News','visibility.activity':'Activity','visibility.chooseGroups':'Choose groups','visibility.createGroupFirst':'Create a group first.'
};
const tr: Dictionary = {
  'groups.loadMembersFailed':'Üyeler yüklenemedi.','groups.deletePrefix':'“','groups.deleteSuffix':'” grubunu silmek istiyor musunuz?','groups.title':'Kullanıcı grupları','groups.subtitle':'Gruplar oluşturun ve hangi üyelerin bu gruplara ait olduğunu seçin.','groups.new':'Yeni grup','groups.empty':'Henüz grup oluşturulmadı.','groups.members':'Üyeler','groups.edit':'Grubu düzenle','groups.name':'Grup adı','groups.description':'Açıklama (isteğe bağlı)','groups.save':'Grubu kaydet','groups.manageMembers':'Üyeleri yönet','groups.searchMember':'Üye ara','groups.noUsers':'Kuruluşta henüz kayıtlı uygulama kullanıcısı yok.','groups.userPrefix':'Kullanıcı ','groups.pending':'Onay bekliyor','groups.cancel':'İptal','groups.saveSelectedPrefix':'Kaydet (','groups.saveSelectedSuffix':')','groups.close':'Kapat','groups.roleMember':'Üye','groups.roleResident':'Sakin','groups.roleVolunteer':'Gönüllü','groups.roleStaff':'Çalışan','groups.roleBoard':'Yönetim kurulu üyesi','groups.roleAdmin':'Yönetici',
  'visibility.public':'Herkese açık','visibility.authenticated':'Tüm giriş yapanlar','visibility.members':'Yalnızca üyeler','visibility.staff':'Yalnızca çalışanlar ve yönetim kurulu','visibility.admins':'Yalnızca yöneticiler','visibility.groups':'Seçili gruplar','visibility.untitled':'Başlıksız','visibility.title':'İçerik bazında erişim','visibility.subtitle':'Her haber ve etkinliği kimlerin görebileceğini belirleyin.','visibility.empty':'Henüz haber veya etkinlik oluşturulmadı.','visibility.news':'Haber','visibility.activity':'Etkinlik','visibility.chooseGroups':'Grupları seç','visibility.createGroupFirst':'Önce bir grup oluşturun.'
};
const ar: Dictionary = {
  'groups.loadMembersFailed':'تعذر تحميل الأعضاء.','groups.deletePrefix':'حذف المجموعة «','groups.deleteSuffix':'»؟','groups.title':'مجموعات المستخدمين','groups.subtitle':'أنشئ مجموعات وحدد الأعضاء الذين ينتمون إليها.','groups.new':'مجموعة جديدة','groups.empty':'لم يتم إنشاء مجموعات بعد.','groups.members':'الأعضاء','groups.edit':'تعديل المجموعة','groups.name':'اسم المجموعة','groups.description':'الوصف (اختياري)','groups.save':'حفظ المجموعة','groups.manageMembers':'إدارة الأعضاء','groups.searchMember':'البحث عن عضو','groups.noUsers':'لا يوجد مستخدمون مسجلون في التطبيق للمؤسسة بعد.','groups.userPrefix':'مستخدم ','groups.pending':'بانتظار الموافقة','groups.cancel':'إلغاء','groups.saveSelectedPrefix':'حفظ (','groups.saveSelectedSuffix':')','groups.close':'إغلاق','groups.roleMember':'عضو','groups.roleResident':'ساكن','groups.roleVolunteer':'متطوع','groups.roleStaff':'موظف','groups.roleBoard':'عضو مجلس الإدارة','groups.roleAdmin':'مسؤول',
  'visibility.public':'عام','visibility.authenticated':'كل المستخدمين المسجلين','visibility.members':'الأعضاء فقط','visibility.staff':'الموظفون ومجلس الإدارة فقط','visibility.admins':'المسؤولون فقط','visibility.groups':'مجموعات محددة','visibility.untitled':'بدون عنوان','visibility.title':'الوصول حسب المحتوى','visibility.subtitle':'حدّد من يمكنه رؤية كل خبر ونشاط.','visibility.empty':'لم يتم إنشاء أخبار أو أنشطة.','visibility.news':'خبر','visibility.activity':'نشاط','visibility.chooseGroups':'اختر المجموعات','visibility.createGroupFirst':'أنشئ مجموعة أولاً.'
};
const ur: Dictionary = {
  'groups.loadMembersFailed':'ارکان لوڈ نہیں ہو سکے۔','groups.deletePrefix':'گروپ “','groups.deleteSuffix':'” حذف کرنا ہے؟','groups.title':'صارف گروپس','groups.subtitle':'گروپس بنائیں اور طے کریں کہ کون سے ارکان ان میں شامل ہیں۔','groups.new':'نیا گروپ','groups.empty':'ابھی کوئی گروپ نہیں بنایا گیا۔','groups.members':'ارکان','groups.edit':'گروپ میں ترمیم','groups.name':'گروپ کا نام','groups.description':'تفصیل (اختیاری)','groups.save':'گروپ محفوظ کریں','groups.manageMembers':'ارکان کا انتظام','groups.searchMember':'رکن تلاش کریں','groups.noUsers':'تنظیم میں ابھی کوئی ایپ صارف رجسٹرڈ نہیں۔','groups.userPrefix':'صارف ','groups.pending':'منظوری کا انتظار','groups.cancel':'منسوخ','groups.saveSelectedPrefix':'محفوظ کریں (','groups.saveSelectedSuffix':')','groups.close':'بند کریں','groups.roleMember':'رکن','groups.roleResident':'رہائشی','groups.roleVolunteer':'رضاکار','groups.roleStaff':'عملہ','groups.roleBoard':'بورڈ رکن','groups.roleAdmin':'ایڈمن',
  'visibility.public':'عوامی','visibility.authenticated':'تمام لاگ اِن صارفین','visibility.members':'صرف ارکان','visibility.staff':'صرف عملہ اور بورڈ','visibility.admins':'صرف ایڈمن','visibility.groups':'منتخب گروپس','visibility.untitled':'بغیر عنوان','visibility.title':'ہر مواد کی رسائی','visibility.subtitle':'طے کریں کہ ہر خبر اور سرگرمی کون دیکھ سکتا ہے۔','visibility.empty':'ابھی کوئی خبر یا سرگرمی نہیں بنائی گئی۔','visibility.news':'خبر','visibility.activity':'سرگرمی','visibility.chooseGroups':'گروپس منتخب کریں','visibility.createGroupFirst':'پہلے گروپ بنائیں۔'
};

const dictionaries: Record<string, Dictionary> = { nb, en, tr, ar, ur };
export function getAccessGroupTranslation(language: string, key: string) {
  return dictionaries[language]?.[key] || en[key] || nb[key] || key;
}
