type Dictionary = Record<string, string>;

const nb: Dictionary = {
  'activities.published':'Publisert','activities.cancelled':'Avlyst','activities.draft':'Utkast','activities.pushFallback':'En ny aktivitet er publisert i appen.','activities.pushTitlePrefix':'Aktivitet: ','activities.supabaseMissing':'Supabase er ikke konfigurert.','activities.tableMissing':'Aktivitetstabellen er ikke klar i Supabase ennå.','activities.titleRequired':'Tittel er obligatorisk.','activities.dateRequired':'Dato er obligatorisk.','activities.capacityInvalid':'Kapasitet må være 0 eller et positivt heltall.','activities.saveFailed':'Aktiviteten kunne ikke lagres.','activities.deleteConfirmPrefix':'Slette aktiviteten «','activities.deleteConfirmSuffix':'»?','activities.deleteFailed':'Aktiviteten kunne ikke slettes: ','activities.pushResent':'Push-varselet ble sendt på nytt.','activities.pushFailed':'Push-varselet kunne ikke sendes.',
  'activities.coreModule':'Kjernemodul','activities.title':'Aktiviteter','activities.countSuffix':'aktiviteter i organisasjonen.','activities.new':'Ny aktivitet','activities.search':'Søk aktivitet eller sted','activities.allStatuses':'Alle statuser','activities.loading':'Henter aktiviteter...','activities.loadFailedTitle':'Aktivitetsmodulen kan ikke laste data','activities.empty':'Ingen aktiviteter funnet','activities.contactPrefix':'Kontakt:','activities.edit':'Rediger','activities.delete':'Slett','activities.pushAgain':'Push igjen','activities.editTitle':'Rediger aktivitet','activities.formTitle':'Tittel','activities.description':'Beskrivelse','activities.date':'Dato','activities.start':'Start','activities.end':'Slutt','activities.location':'Sted','activities.capacity':'Kapasitet','activities.contactOptional':'Kontaktperson (valgfritt)','activities.contactHelp':'Bare aktive og offentlige kontaktpersoner kan velges.','activities.searchContact':'Søk kontaktperson','activities.noContact':'Ingen kontaktperson','activities.status':'Status','activities.sendPush':'Send push-varsel','activities.pushEditHelp':'Av som standard ved redigering. Slå på bare når du ønsker nytt varsel.','activities.pushCreateHelp':'Slå av dersom aktiviteten skal lagres uten varsel.','activities.saving':'Lagrer...','activities.saveChanges':'Lagre endringer','activities.create':'Opprett aktivitet','activities.close':'Lukk'
};
const en: Dictionary = {
  'activities.published':'Published','activities.cancelled':'Cancelled','activities.draft':'Draft','activities.pushFallback':'A new activity has been published in the app.','activities.pushTitlePrefix':'Activity: ','activities.supabaseMissing':'Supabase is not configured.','activities.tableMissing':'The activity table is not ready in Supabase yet.','activities.titleRequired':'Title is required.','activities.dateRequired':'Date is required.','activities.capacityInvalid':'Capacity must be 0 or a positive whole number.','activities.saveFailed':'The activity could not be saved.','activities.deleteConfirmPrefix':'Delete the activity “','activities.deleteConfirmSuffix':'”?','activities.deleteFailed':'The activity could not be deleted: ','activities.pushResent':'The push notification was sent again.','activities.pushFailed':'The push notification could not be sent.',
  'activities.coreModule':'Core module','activities.title':'Activities','activities.countSuffix':'activities in the organization.','activities.new':'New activity','activities.search':'Search activity or location','activities.allStatuses':'All statuses','activities.loading':'Loading activities...','activities.loadFailedTitle':'The activity module cannot load data','activities.empty':'No activities found','activities.contactPrefix':'Contact:','activities.edit':'Edit','activities.delete':'Delete','activities.pushAgain':'Push again','activities.editTitle':'Edit activity','activities.formTitle':'Title','activities.description':'Description','activities.date':'Date','activities.start':'Start','activities.end':'End','activities.location':'Location','activities.capacity':'Capacity','activities.contactOptional':'Contact person (optional)','activities.contactHelp':'Only active and publicly visible contacts can be selected.','activities.searchContact':'Search contact person','activities.noContact':'No contact person','activities.status':'Status','activities.sendPush':'Send push notification','activities.pushEditHelp':'Off by default when editing. Turn it on only when you want a new notification.','activities.pushCreateHelp':'Turn it off if the activity should be saved without a notification.','activities.saving':'Saving...','activities.saveChanges':'Save changes','activities.create':'Create activity','activities.close':'Close'
};
const tr: Dictionary = {
  'activities.published':'Yayınlandı','activities.cancelled':'İptal edildi','activities.draft':'Taslak','activities.pushFallback':'Uygulamada yeni bir etkinlik yayınlandı.','activities.pushTitlePrefix':'Etkinlik: ','activities.supabaseMissing':'Supabase yapılandırılmamış.','activities.tableMissing':'Etkinlik tablosu Supabase’de henüz hazır değil.','activities.titleRequired':'Başlık zorunludur.','activities.dateRequired':'Tarih zorunludur.','activities.capacityInvalid':'Kapasite 0 veya pozitif bir tam sayı olmalıdır.','activities.saveFailed':'Etkinlik kaydedilemedi.','activities.deleteConfirmPrefix':'“','activities.deleteConfirmSuffix':'” etkinliğini silmek istiyor musunuz?','activities.deleteFailed':'Etkinlik silinemedi: ','activities.pushResent':'Push bildirimi yeniden gönderildi.','activities.pushFailed':'Push bildirimi gönderilemedi.',
  'activities.coreModule':'Temel modül','activities.title':'Etkinlikler','activities.countSuffix':'etkinlik kayıtlı.','activities.new':'Yeni etkinlik','activities.search':'Etkinlik veya konum ara','activities.allStatuses':'Tüm durumlar','activities.loading':'Etkinlikler yükleniyor...','activities.loadFailedTitle':'Etkinlik modülü verileri yükleyemiyor','activities.empty':'Etkinlik bulunamadı','activities.contactPrefix':'İletişim:','activities.edit':'Düzenle','activities.delete':'Sil','activities.pushAgain':'Push tekrar','activities.editTitle':'Etkinliği düzenle','activities.formTitle':'Başlık','activities.description':'Açıklama','activities.date':'Tarih','activities.start':'Başlangıç','activities.end':'Bitiş','activities.location':'Konum','activities.capacity':'Kapasite','activities.contactOptional':'İletişim kişisi (isteğe bağlı)','activities.contactHelp':'Yalnızca aktif ve herkese açık iletişim kişileri seçilebilir.','activities.searchContact':'İletişim kişisi ara','activities.noContact':'İletişim kişisi yok','activities.status':'Durum','activities.sendPush':'Push bildirimi gönder','activities.pushEditHelp':'Düzenlemede varsayılan olarak kapalıdır. Yeni bildirim için açın.','activities.pushCreateHelp':'Etkinlik bildirim olmadan kaydedilecekse kapatın.','activities.saving':'Kaydediliyor...','activities.saveChanges':'Değişiklikleri kaydet','activities.create':'Etkinlik oluştur','activities.close':'Kapat'
};
const ar: Dictionary = {
  'activities.published':'منشور','activities.cancelled':'ملغى','activities.draft':'مسودة','activities.pushFallback':'تم نشر نشاط جديد في التطبيق.','activities.pushTitlePrefix':'نشاط: ','activities.supabaseMissing':'لم يتم إعداد Supabase.','activities.tableMissing':'جدول الأنشطة غير جاهز في Supabase بعد.','activities.titleRequired':'العنوان مطلوب.','activities.dateRequired':'التاريخ مطلوب.','activities.capacityInvalid':'يجب أن تكون السعة 0 أو عدداً صحيحاً موجباً.','activities.saveFailed':'تعذر حفظ النشاط.','activities.deleteConfirmPrefix':'هل تريد حذف النشاط «','activities.deleteConfirmSuffix':'»؟','activities.deleteFailed':'تعذر حذف النشاط: ','activities.pushResent':'تم إرسال الإشعار مرة أخرى.','activities.pushFailed':'تعذر إرسال الإشعار.',
  'activities.coreModule':'وحدة أساسية','activities.title':'الأنشطة','activities.countSuffix':'أنشطة في المؤسسة.','activities.new':'نشاط جديد','activities.search':'البحث عن نشاط أو موقع','activities.allStatuses':'كل الحالات','activities.loading':'جارٍ تحميل الأنشطة...','activities.loadFailedTitle':'تعذر تحميل بيانات وحدة الأنشطة','activities.empty':'لم يتم العثور على أنشطة','activities.contactPrefix':'جهة الاتصال:','activities.edit':'تعديل','activities.delete':'حذف','activities.pushAgain':'إرسال الإشعار مجدداً','activities.editTitle':'تعديل النشاط','activities.formTitle':'العنوان','activities.description':'الوصف','activities.date':'التاريخ','activities.start':'البداية','activities.end':'النهاية','activities.location':'الموقع','activities.capacity':'السعة','activities.contactOptional':'جهة الاتصال (اختياري)','activities.contactHelp':'يمكن اختيار جهات الاتصال النشطة والظاهرة للعامة فقط.','activities.searchContact':'البحث عن جهة اتصال','activities.noContact':'لا توجد جهة اتصال','activities.status':'الحالة','activities.sendPush':'إرسال إشعار','activities.pushEditHelp':'مغلق افتراضياً عند التعديل. فعّله فقط لإرسال إشعار جديد.','activities.pushCreateHelp':'أوقفه إذا أردت حفظ النشاط دون إشعار.','activities.saving':'جارٍ الحفظ...','activities.saveChanges':'حفظ التغييرات','activities.create':'إنشاء النشاط','activities.close':'إغلاق'
};
const ur: Dictionary = {
  'activities.published':'شائع شدہ','activities.cancelled':'منسوخ','activities.draft':'مسودہ','activities.pushFallback':'ایپ میں نئی سرگرمی شائع ہوئی ہے۔','activities.pushTitlePrefix':'سرگرمی: ','activities.supabaseMissing':'Supabase ترتیب نہیں دیا گیا۔','activities.tableMissing':'سرگرمیوں کی جدول Supabase میں ابھی تیار نہیں۔','activities.titleRequired':'عنوان ضروری ہے۔','activities.dateRequired':'تاریخ ضروری ہے۔','activities.capacityInvalid':'گنجائش 0 یا مثبت مکمل عدد ہونی چاہیے۔','activities.saveFailed':'سرگرمی محفوظ نہیں ہو سکی۔','activities.deleteConfirmPrefix':'کیا سرگرمی “','activities.deleteConfirmSuffix':'” حذف کرنی ہے؟','activities.deleteFailed':'سرگرمی حذف نہیں ہو سکی: ','activities.pushResent':'پش اطلاع دوبارہ بھیج دی گئی۔','activities.pushFailed':'پش اطلاع نہیں بھیجی جا سکی۔',
  'activities.coreModule':'بنیادی ماڈیول','activities.title':'سرگرمیاں','activities.countSuffix':'سرگرمیاں تنظیم میں۔','activities.new':'نئی سرگرمی','activities.search':'سرگرمی یا مقام تلاش کریں','activities.allStatuses':'تمام حالتیں','activities.loading':'سرگرمیاں لوڈ ہو رہی ہیں...','activities.loadFailedTitle':'سرگرمیوں کا ماڈیول ڈیٹا لوڈ نہیں کر سکا','activities.empty':'کوئی سرگرمی نہیں ملی','activities.contactPrefix':'رابطہ:','activities.edit':'ترمیم','activities.delete':'حذف','activities.pushAgain':'پش دوبارہ','activities.editTitle':'سرگرمی میں ترمیم','activities.formTitle':'عنوان','activities.description':'تفصیل','activities.date':'تاریخ','activities.start':'آغاز','activities.end':'اختتام','activities.location':'مقام','activities.capacity':'گنجائش','activities.contactOptional':'رابطہ شخص (اختیاری)','activities.contactHelp':'صرف فعال اور عوامی رابطہ افراد منتخب کیے جا سکتے ہیں۔','activities.searchContact':'رابطہ شخص تلاش کریں','activities.noContact':'کوئی رابطہ شخص نہیں','activities.status':'حالت','activities.sendPush':'پش اطلاع بھیجیں','activities.pushEditHelp':'ترمیم کے وقت بطور ڈیفالٹ بند ہے۔ نئی اطلاع کے لیے فعال کریں۔','activities.pushCreateHelp':'سرگرمی بغیر اطلاع کے محفوظ کرنی ہو تو بند کریں۔','activities.saving':'محفوظ ہو رہا ہے...','activities.saveChanges':'تبدیلیاں محفوظ کریں','activities.create':'سرگرمی بنائیں','activities.close':'بند کریں'
};

const dictionaries: Record<string, Dictionary> = { nb, en, tr, ar, ur };
export function getActivityTranslation(language: string, key: string) {
  return dictionaries[language]?.[key] || en[key] || nb[key] || key;
}
