import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { findLanguage } from './languageRegistry';
import { DEFAULT_ORGANIZATION_ID } from './organization';
import { supabase } from './supabase';

type Dictionary = Record<string, string>;

const nb: Dictionary = {
  'nav.home':'Hjem','nav.donation':'Donasjon','nav.contact':'Kontakt',
  'contact.title':'Kontakt','contact.subtitle':'Ta kontakt med oss','contact.location':'FYSISK ADRESSE','contact.address':'Organisasjonens adresse','contact.directions':'FINN FREM','contact.askTitle':'Still et spørsmål','contact.askSubtitle':'Send spørsmålet ditt via WhatsApp','contact.askBody':'Har du spørsmål? Kontakt organisasjonen via WhatsApp, så hjelper vi deg så snart som mulig.','contact.askButton':'SPØR VIA WHATSAPP','contact.staff':'Våre kontaktpersoner','contact.noStaff':'Ingen kontaktpersoner er registrert ennå.','contact.call':'Ring',
  'home.changeCity':'Endre by','home.searchCity':'Søk etter by...','home.useLocation':'Bruk min posisjon','home.nextPrayer':'Neste','home.loadingPrayer':'Henter bønnetider...','home.todayProgram':'Dagens program','home.upcomingActivities':'Kommende aktiviteter','home.noUpcomingActivities':'Ingen kommende aktiviteter.','home.news':'Nyheter','home.noNews':'Ingen nyheter ennå.',
  'install.title':'Installer appen','install.description':'Legg den til på startskjermen for rask tilgang','install.button':'Installer','install.close':'Lukk',
  'common.loading':'Laster...','common.close':'Lukk','common.save':'Lagre','common.saving':'Lagrer...',
  'recovery.title':'Velg nytt passord','recovery.password':'Nytt passord','recovery.repeat':'Gjenta nytt passord','recovery.show':'Vis passord','recovery.tooShort':'Passordet må ha minst 6 tegn.','recovery.noMatch':'Passordene er ikke like.','recovery.noConnection':'Ingen forbindelse til systemet.','recovery.failed':'Passordet kunne ikke lagres: ','recovery.success':'Passordet er lagret. Du kan nå logge inn med det nye passordet.',
  'login.title':'Administratorinnlogging','login.email':'E-post','login.password':'Passord','login.submit':'Logg inn','login.invalid':'Feil e-post eller passord.','login.forgotPassword':'Glemt passord?','login.temporaryPassword':'Du har logget inn med et midlertidig passord. Velg et permanent passord før du fortsetter.','login.showPasswords':'Vis passordene','login.savePassword':'Lagre nytt passord','login.passwordUpdateFailed':'Passordet kunne ikke oppdateres: ',
  'forgot.title':'Tilbakestill passord','forgot.description':'Skriv inn e-postadressen din. Du får tilsendt en sikker lenke for å velge nytt passord.','forgot.emailRequired':'E-post er obligatorisk.','forgot.sendFailed':'E-posten kunne ikke sendes: ','forgot.sent':'En lenke for tilbakestilling er sendt til e-postadressen din.','forgot.submit':'Send tilbakestillingslenke',
  'installGuide.title':'Installer appen','installGuide.subtitle':'Legg appen til på startskjermen','installGuide.iosShareTitle':'Trykk på Del','installGuide.iosShareBody':'Trykk på Del-knappen nederst i Safari.','installGuide.share':'Del','installGuide.bottomOfScreen':'Nederst på skjermen','installGuide.addHomeTitle':'Velg Legg til på Hjem-skjerm','installGuide.iosAddHomeBody':'Rull ned i menyen og trykk på «Legg til på Hjem-skjerm».','installGuide.addHome':'Legg til på Hjem-skjerm','installGuide.doneTitle':'Ferdig!','installGuide.doneBody':'Appikonet vises nå på startskjermen, og appen kan åpnes direkte derfra.','installGuide.openMenuTitle':'Åpne nettlesermenyen','installGuide.samsungMenuBody':'Trykk på menyikonet i Samsung Internet.','installGuide.topRight':'Øverst til høyre','installGuide.menu':'Meny','installGuide.samsungAddHomeBody':'Velg «Legg til side på» og deretter startskjermen.','installGuide.browserMenu':'Nettlesermeny','installGuide.genericBody':'Åpne nettlesermenyen og velg «Legg til på startskjermen» eller «Installer app».','installGuide.doneShort':'Appikonet vises nå på startskjermen.','installGuide.understood':'Forstått',
  'activity.label':'Aktivitet','activity.contact':'Kontaktperson','activity.addCalendar':'Legg til i kalender','activity.addReminder':'Legg til påminnelse','activity.call':'Ring','activity.sms':'SMS','activity.whatsapp':'WhatsApp','activity.email':'E-post',
  'donation.title':'Støtt arbeidet vårt','donation.subtitle':'Bidraget ditt støtter organisasjonens aktiviteter og arbeid.','donation.copyNumber':'Kopier nummer','donation.copied':'Kopiert','donation.openVipps':'Åpne i Vipps','donation.openingVipps':'Åpner Vipps...','donation.vippsDisabled':'Vipps-lenken er deaktivert. Du kan kopiere nummeret for å bidra.','donation.note':'Alle bidrag brukes til organisasjonens aktiviteter, tilbud og samfunnsnyttige arbeid.'
};

const en: Dictionary = {
  'nav.home':'Home','nav.donation':'Donate','nav.contact':'Contact',
  'contact.title':'Contact','contact.subtitle':'Get in touch with us','contact.location':'PHYSICAL LOCATION','contact.address':'Organization address','contact.directions':'GET DIRECTIONS','contact.askTitle':'Ask a question','contact.askSubtitle':'Send your question via WhatsApp','contact.askBody':'Do you have a question? Contact the organization through WhatsApp and we will help as soon as possible.','contact.askButton':'ASK ON WHATSAPP','contact.staff':'Our contacts','contact.noStaff':'No contacts have been registered yet.','contact.call':'Call',
  'home.changeCity':'Change city','home.searchCity':'Search city...','home.useLocation':'Use my location','home.nextPrayer':'Next','home.loadingPrayer':'Loading prayer times...','home.todayProgram':'Today’s program','home.upcomingActivities':'Upcoming activities','home.noUpcomingActivities':'No upcoming activities.','home.news':'News','home.noNews':'No news yet.',
  'install.title':'Install the app','install.description':'Add it to your home screen for quick access','install.button':'Install','install.close':'Close',
  'common.loading':'Loading...','common.close':'Close','common.save':'Save','common.saving':'Saving...',
  'recovery.title':'Choose a new password','recovery.password':'New password','recovery.repeat':'Repeat new password','recovery.show':'Show password','recovery.tooShort':'The password must contain at least 6 characters.','recovery.noMatch':'The passwords do not match.','recovery.noConnection':'No connection to the system.','recovery.failed':'The password could not be saved: ','recovery.success':'The password has been saved. You can now sign in with the new password.',
  'login.title':'Administrator sign in','login.email':'Email','login.password':'Password','login.submit':'Sign in','login.invalid':'Incorrect email or password.','login.forgotPassword':'Forgot password?','login.temporaryPassword':'You signed in with a temporary password. Choose a permanent password before continuing.','login.showPasswords':'Show passwords','login.savePassword':'Save new password','login.passwordUpdateFailed':'The password could not be updated: ',
  'forgot.title':'Reset password','forgot.description':'Enter your email address. We will send you a secure link to choose a new password.','forgot.emailRequired':'Email is required.','forgot.sendFailed':'The reset email could not be sent: ','forgot.sent':'A password reset link has been sent to your email address.','forgot.submit':'Send reset link',
  'installGuide.title':'Install the app','installGuide.subtitle':'Add the app to your home screen','installGuide.iosShareTitle':'Tap Share','installGuide.iosShareBody':'Tap the Share button at the bottom of Safari.','installGuide.share':'Share','installGuide.bottomOfScreen':'Bottom of screen','installGuide.addHomeTitle':'Choose Add to Home Screen','installGuide.iosAddHomeBody':'Scroll down in the menu and tap “Add to Home Screen”.','installGuide.addHome':'Add to Home Screen','installGuide.doneTitle':'Done!','installGuide.doneBody':'The app icon is now on your home screen and can be opened directly from there.','installGuide.openMenuTitle':'Open the browser menu','installGuide.samsungMenuBody':'Tap the menu icon in Samsung Internet.','installGuide.topRight':'Top right','installGuide.menu':'Menu','installGuide.samsungAddHomeBody':'Choose “Add page to” and then Home screen.','installGuide.browserMenu':'Browser menu','installGuide.genericBody':'Open the browser menu and choose “Add to Home screen” or “Install app”.','installGuide.doneShort':'The app icon is now on your home screen.','installGuide.understood':'Got it',
  'activity.label':'Activity','activity.contact':'Contact person','activity.addCalendar':'Add to calendar','activity.addReminder':'Add reminder','activity.call':'Call','activity.sms':'SMS','activity.whatsapp':'WhatsApp','activity.email':'Email',
  'donation.title':'Support our work','donation.subtitle':'Your contribution supports the organization’s activities and work.','donation.copyNumber':'Copy number','donation.copied':'Copied','donation.openVipps':'Open in Vipps','donation.openingVipps':'Opening Vipps...','donation.vippsDisabled':'The Vipps link is disabled. You can copy the number to contribute.','donation.note':'All contributions support the organization’s activities, services and community work.'
};

const tr: Dictionary = {
  'nav.home':'Ana Sayfa','nav.donation':'Bağış','nav.contact':'İletişim',
  'contact.title':'İletişim','contact.subtitle':'Bizimle iletişime geçin','contact.location':'FİZİKSEL KONUM','contact.address':'Dernek adresi','contact.directions':'YOL TARİFİ','contact.askTitle':'Soru Sor','contact.askSubtitle':'Sorunuzu WhatsApp üzerinden iletin','contact.askBody':'Sorunuz mu var? WhatsApp üzerinden kuruluşla iletişime geçebilirsiniz.','contact.askButton':'WHATSAPP İLE SOR','contact.staff':'İletişim kişilerimiz','contact.noStaff':'Henüz kayıtlı kişi yok.','contact.call':'Ara',
  'home.changeCity':'Şehir Değiştir','home.searchCity':'Şehir ara...','home.useLocation':'Konumumu kullan','home.nextPrayer':'Sıradaki','home.loadingPrayer':'Namaz vakitleri yükleniyor...','home.todayProgram':'Bugünkü program','home.upcomingActivities':'Yaklaşan aktiviteler','home.noUpcomingActivities':'Yaklaşan aktivite yok.','home.news':'Haberler','home.noNews':'Henüz haber yok.',
  'install.title':'Uygulamayı Yükle','install.description':'Ana ekrana ekleyin, hızlı erişin','install.button':'Yükle','install.close':'Kapat',
  'common.loading':'Yükleniyor...','common.close':'Kapat','common.save':'Kaydet','common.saving':'Kaydediliyor...',
  'recovery.title':'Yeni şifre belirle','recovery.password':'Yeni şifre','recovery.repeat':'Yeni şifre tekrar','recovery.show':'Şifreyi göster','recovery.tooShort':'Şifre en az 6 karakter olmalıdır.','recovery.noMatch':'Şifreler aynı değil.','recovery.noConnection':'Sistem bağlantısı yok.','recovery.failed':'Şifre kaydedilemedi: ','recovery.success':'Şifre kaydedildi. Yeni şifrenizle giriş yapabilirsiniz.',
  'login.title':'Yönetici Girişi','login.email':'E-posta','login.password':'Şifre','login.submit':'Giriş Yap','login.invalid':'E-posta veya şifre hatalı.','login.forgotPassword':'Şifremi unuttum','login.temporaryPassword':'Geçici şifre ile giriş yaptınız. Devam etmeden önce kalıcı bir şifre belirleyin.','login.showPasswords':'Şifreleri göster','login.savePassword':'Yeni Şifreyi Kaydet','login.passwordUpdateFailed':'Şifre güncellenemedi: ',
  'forgot.title':'Şifreyi Sıfırla','forgot.description':'E-posta adresinizi girin. Yeni bir şifre seçmeniz için güvenli bir bağlantı göndereceğiz.','forgot.emailRequired':'E-posta zorunludur.','forgot.sendFailed':'Sıfırlama e-postası gönderilemedi: ','forgot.sent':'Şifre sıfırlama bağlantısı e-posta adresinize gönderildi.','forgot.submit':'Sıfırlama bağlantısı gönder',
  'installGuide.title':'Uygulamayı Yükle','installGuide.subtitle':'Uygulamayı ana ekranınıza ekleyin','installGuide.iosShareTitle':'Paylaş’a dokunun','installGuide.iosShareBody':'Safari’nin altındaki Paylaş düğmesine dokunun.','installGuide.share':'Paylaş','installGuide.bottomOfScreen':'Ekranın altında','installGuide.addHomeTitle':'Ana Ekrana Ekle’yi seçin','installGuide.iosAddHomeBody':'Menüde aşağı kaydırın ve “Ana Ekrana Ekle”ye dokunun.','installGuide.addHome':'Ana Ekrana Ekle','installGuide.doneTitle':'Tamamlandı!','installGuide.doneBody':'Uygulama simgesi ana ekranınızda görünür ve uygulamayı doğrudan buradan açabilirsiniz.','installGuide.openMenuTitle':'Tarayıcı menüsünü açın','installGuide.samsungMenuBody':'Samsung Internet menü simgesine dokunun.','installGuide.topRight':'Sağ üst','installGuide.menu':'Menü','installGuide.samsungAddHomeBody':'“Sayfayı ekle” ve ardından Ana ekran seçeneğini seçin.','installGuide.browserMenu':'Tarayıcı menüsü','installGuide.genericBody':'Tarayıcı menüsünü açın ve “Ana ekrana ekle” veya “Uygulamayı yükle” seçeneğini seçin.','installGuide.doneShort':'Uygulama simgesi artık ana ekranınızda.','installGuide.understood':'Anladım',
  'activity.label':'Aktivite','activity.contact':'İletişim kişisi','activity.addCalendar':'Takvime ekle','activity.addReminder':'Hatırlatıcı ekle','activity.call':'Ara','activity.sms':'SMS','activity.whatsapp':'WhatsApp','activity.email':'E-posta',
  'donation.title':'Çalışmalarımızı Destekleyin','donation.subtitle':'Katkınız kuruluşun faaliyetlerini ve çalışmalarını destekler.','donation.copyNumber':'Numarayı Kopyala','donation.copied':'Kopyalandı','donation.openVipps':'Vipps’te Aç','donation.openingVipps':'Vipps Açılıyor...','donation.vippsDisabled':'Vipps bağlantısı kapalı. Katkıda bulunmak için numarayı kopyalayabilirsiniz.','donation.note':'Tüm katkılar kuruluşun faaliyetleri, hizmetleri ve toplum yararına çalışmaları için kullanılır.'
};

const ar: Dictionary = {
  'nav.home':'الرئيسية','nav.donation':'تبرع','nav.contact':'اتصل بنا',
  'contact.title':'اتصل بنا','contact.subtitle':'تواصل معنا','contact.location':'الموقع','contact.address':'عنوان المؤسسة','contact.directions':'الاتجاهات','contact.askTitle':'اطرح سؤالاً','contact.askSubtitle':'أرسل سؤالك عبر واتساب','contact.askBody':'هل لديك سؤال؟ تواصل مع المؤسسة عبر واتساب وسنساعدك في أقرب وقت.','contact.askButton':'اسأل عبر واتساب','contact.staff':'جهات الاتصال','contact.noStaff':'لا توجد جهات اتصال مسجلة بعد.','contact.call':'اتصال',
  'home.changeCity':'تغيير المدينة','home.searchCity':'ابحث عن مدينة...','home.useLocation':'استخدم موقعي','home.nextPrayer':'التالي','home.loadingPrayer':'جارٍ تحميل مواقيت الصلاة...','home.todayProgram':'برنامج اليوم','home.upcomingActivities':'الأنشطة القادمة','home.noUpcomingActivities':'لا توجد أنشطة قادمة.','home.news':'الأخبار','home.noNews':'لا توجد أخبار بعد.',
  'install.title':'ثبّت التطبيق','install.description':'أضفه إلى الشاشة الرئيسية للوصول السريع','install.button':'تثبيت','install.close':'إغلاق',
  'common.loading':'جارٍ التحميل...','common.close':'إغلاق','common.save':'حفظ','common.saving':'جارٍ الحفظ...',
  'recovery.title':'اختر كلمة مرور جديدة','recovery.password':'كلمة المرور الجديدة','recovery.repeat':'أعد كتابة كلمة المرور','recovery.show':'إظهار كلمة المرور','recovery.tooShort':'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.','recovery.noMatch':'كلمتا المرور غير متطابقتين.','recovery.noConnection':'لا يوجد اتصال بالنظام.','recovery.failed':'تعذر حفظ كلمة المرور: ','recovery.success':'تم حفظ كلمة المرور. يمكنك الآن تسجيل الدخول باستخدامها.',
  'login.title':'تسجيل دخول المسؤول','login.email':'البريد الإلكتروني','login.password':'كلمة المرور','login.submit':'تسجيل الدخول','login.invalid':'البريد الإلكتروني أو كلمة المرور غير صحيحة.','login.forgotPassword':'نسيت كلمة المرور؟','login.temporaryPassword':'لقد سجلت الدخول بكلمة مرور مؤقتة. اختر كلمة مرور دائمة قبل المتابعة.','login.showPasswords':'إظهار كلمات المرور','login.savePassword':'حفظ كلمة المرور الجديدة','login.passwordUpdateFailed':'تعذر تحديث كلمة المرور: ',
  'forgot.title':'إعادة تعيين كلمة المرور','forgot.description':'أدخل بريدك الإلكتروني وسنرسل لك رابطاً آمناً لاختيار كلمة مرور جديدة.','forgot.emailRequired':'البريد الإلكتروني مطلوب.','forgot.sendFailed':'تعذر إرسال رسالة إعادة التعيين: ','forgot.sent':'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني.','forgot.submit':'إرسال رابط إعادة التعيين',
  'installGuide.title':'تثبيت التطبيق','installGuide.subtitle':'أضف التطبيق إلى الشاشة الرئيسية','installGuide.iosShareTitle':'اضغط على مشاركة','installGuide.iosShareBody':'اضغط على زر المشاركة أسفل Safari.','installGuide.share':'مشاركة','installGuide.bottomOfScreen':'أسفل الشاشة','installGuide.addHomeTitle':'اختر الإضافة إلى الشاشة الرئيسية','installGuide.iosAddHomeBody':'مرّر لأسفل واضغط على “إضافة إلى الشاشة الرئيسية”.','installGuide.addHome':'إضافة إلى الشاشة الرئيسية','installGuide.doneTitle':'تم!','installGuide.doneBody':'سيظهر رمز التطبيق على الشاشة الرئيسية ويمكن فتحه مباشرة من هناك.','installGuide.openMenuTitle':'افتح قائمة المتصفح','installGuide.samsungMenuBody':'اضغط على رمز القائمة في Samsung Internet.','installGuide.topRight':'أعلى اليمين','installGuide.menu':'القائمة','installGuide.samsungAddHomeBody':'اختر “إضافة الصفحة إلى” ثم الشاشة الرئيسية.','installGuide.browserMenu':'قائمة المتصفح','installGuide.genericBody':'افتح قائمة المتصفح واختر “إضافة إلى الشاشة الرئيسية” أو “تثبيت التطبيق”.','installGuide.doneShort':'رمز التطبيق موجود الآن على الشاشة الرئيسية.','installGuide.understood':'فهمت',
  'activity.label':'نشاط','activity.contact':'جهة الاتصال','activity.addCalendar':'إضافة إلى التقويم','activity.addReminder':'إضافة تذكير','activity.call':'اتصال','activity.sms':'رسالة نصية','activity.whatsapp':'واتساب','activity.email':'بريد إلكتروني',
  'donation.title':'ادعم عملنا','donation.subtitle':'تساهم مساهمتك في دعم أنشطة المؤسسة وعملها.','donation.copyNumber':'نسخ الرقم','donation.copied':'تم النسخ','donation.openVipps':'فتح في Vipps','donation.openingVipps':'جارٍ فتح Vipps...','donation.vippsDisabled':'رابط Vipps غير مفعّل. يمكنك نسخ الرقم للمساهمة.','donation.note':'تُستخدم جميع المساهمات لدعم أنشطة المؤسسة وخدماتها وعملها المجتمعي.'
};

const ur: Dictionary = {
  'nav.home':'ہوم','nav.donation':'عطیہ','nav.contact':'رابطہ',
  'contact.title':'رابطہ','contact.subtitle':'ہم سے رابطہ کریں','contact.location':'مقام','contact.address':'تنظیم کا پتہ','contact.directions':'راستہ دیکھیں','contact.askTitle':'سوال پوچھیں','contact.askSubtitle':'واٹس ایپ کے ذریعے سوال بھیجیں','contact.askBody':'کیا آپ کا کوئی سوال ہے؟ واٹس ایپ کے ذریعے تنظیم سے رابطہ کریں۔','contact.askButton':'واٹس ایپ پر پوچھیں','contact.staff':'رابطہ افراد','contact.noStaff':'ابھی کوئی رابطہ فرد درج نہیں ہے۔','contact.call':'کال کریں',
  'home.changeCity':'شہر تبدیل کریں','home.searchCity':'شہر تلاش کریں...','home.useLocation':'میرا مقام استعمال کریں','home.nextPrayer':'اگلی نماز','home.loadingPrayer':'نماز کے اوقات لوڈ ہو رہے ہیں...','home.todayProgram':'آج کا پروگرام','home.upcomingActivities':'آنے والی سرگرمیاں','home.noUpcomingActivities':'کوئی آنے والی سرگرمی نہیں۔','home.news':'خبریں','home.noNews':'ابھی کوئی خبر نہیں۔',
  'install.title':'ایپ انسٹال کریں','install.description':'فوری رسائی کے لیے ہوم اسکرین پر شامل کریں','install.button':'انسٹال','install.close':'بند کریں',
  'common.loading':'لوڈ ہو رہا ہے...','common.close':'بند کریں','common.save':'محفوظ کریں','common.saving':'محفوظ ہو رہا ہے...',
  'recovery.title':'نیا پاس ورڈ منتخب کریں','recovery.password':'نیا پاس ورڈ','recovery.repeat':'نیا پاس ورڈ دوبارہ لکھیں','recovery.show':'پاس ورڈ دکھائیں','recovery.tooShort':'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے۔','recovery.noMatch':'پاس ورڈ ایک جیسے نہیں ہیں۔','recovery.noConnection':'سسٹم سے رابطہ نہیں ہے۔','recovery.failed':'پاس ورڈ محفوظ نہیں ہو سکا: ','recovery.success':'پاس ورڈ محفوظ ہو گیا۔ اب آپ نئے پاس ورڈ سے لاگ ان کر سکتے ہیں۔',
  'login.title':'ایڈمن لاگ اِن','login.email':'ای میل','login.password':'پاس ورڈ','login.submit':'لاگ اِن','login.invalid':'ای میل یا پاس ورڈ درست نہیں۔','login.forgotPassword':'پاس ورڈ بھول گئے؟','login.temporaryPassword':'آپ نے عارضی پاس ورڈ سے لاگ اِن کیا ہے۔ جاری رکھنے سے پہلے مستقل پاس ورڈ منتخب کریں۔','login.showPasswords':'پاس ورڈ دکھائیں','login.savePassword':'نیا پاس ورڈ محفوظ کریں','login.passwordUpdateFailed':'پاس ورڈ اپ ڈیٹ نہیں ہو سکا: ',
  'forgot.title':'پاس ورڈ ری سیٹ کریں','forgot.description':'اپنا ای میل درج کریں۔ نیا پاس ورڈ منتخب کرنے کے لیے محفوظ لنک بھیجا جائے گا۔','forgot.emailRequired':'ای میل ضروری ہے۔','forgot.sendFailed':'ری سیٹ ای میل نہیں بھیجی جا سکی: ','forgot.sent':'پاس ورڈ ری سیٹ لنک آپ کے ای میل پر بھیج دیا گیا ہے۔','forgot.submit':'ری سیٹ لنک بھیجیں',
  'installGuide.title':'ایپ انسٹال کریں','installGuide.subtitle':'ایپ کو ہوم اسکرین پر شامل کریں','installGuide.iosShareTitle':'شیئر پر ٹیپ کریں','installGuide.iosShareBody':'Safari کے نیچے شیئر بٹن پر ٹیپ کریں۔','installGuide.share':'شیئر','installGuide.bottomOfScreen':'اسکرین کے نیچے','installGuide.addHomeTitle':'ہوم اسکرین میں شامل کریں منتخب کریں','installGuide.iosAddHomeBody':'مینو میں نیچے جائیں اور “Add to Home Screen” پر ٹیپ کریں۔','installGuide.addHome':'ہوم اسکرین میں شامل کریں','installGuide.doneTitle':'مکمل!','installGuide.doneBody':'ایپ آئیکن ہوم اسکرین پر ظاہر ہوگا اور وہیں سے کھولا جا سکے گا۔','installGuide.openMenuTitle':'براؤزر مینو کھولیں','installGuide.samsungMenuBody':'Samsung Internet کے مینو آئیکن پر ٹیپ کریں۔','installGuide.topRight':'اوپر دائیں','installGuide.menu':'مینو','installGuide.samsungAddHomeBody':'“Add page to” اور پھر Home screen منتخب کریں۔','installGuide.browserMenu':'براؤزر مینو','installGuide.genericBody':'براؤزر مینو کھولیں اور “Add to Home screen” یا “Install app” منتخب کریں۔','installGuide.doneShort':'ایپ آئیکن اب ہوم اسکرین پر ہے۔','installGuide.understood':'سمجھ گیا',
  'activity.label':'سرگرمی','activity.contact':'رابطہ فرد','activity.addCalendar':'کیلنڈر میں شامل کریں','activity.addReminder':'یاد دہانی شامل کریں','activity.call':'کال','activity.sms':'ایس ایم ایس','activity.whatsapp':'واٹس ایپ','activity.email':'ای میل',
  'donation.title':'ہمارے کام کی حمایت کریں','donation.subtitle':'آپ کی شراکت تنظیم کی سرگرمیوں اور کام کی حمایت کرتی ہے۔','donation.copyNumber':'نمبر کاپی کریں','donation.copied':'کاپی ہو گیا','donation.openVipps':'Vipps میں کھولیں','donation.openingVipps':'Vipps کھل رہا ہے...','donation.vippsDisabled':'Vipps لنک غیر فعال ہے۔ تعاون کے لیے نمبر کاپی کریں۔','donation.note':'تمام تعاون تنظیم کی سرگرمیوں، خدمات اور سماجی کام کے لیے استعمال ہوتا ہے۔'
};

const dictionaries: Record<string, Dictionary> = { nb, en, tr, ar, ur };

type I18nValue = { language:string; direction:'ltr'|'rtl'; locale:string; t:(key:string)=>string; reload:()=>Promise<void> };
const I18nContext = createContext<I18nValue>({ language:'nb', direction:'ltr', locale:'nb-NO', t:(key)=>nb[key]||key, reload:async()=>{} });

export function AppI18nProvider({ children }: { children: ReactNode }) {
  const [language,setLanguage]=useState('nb');
  const load=async()=>{
    if(!supabase)return;
    const {data}=await supabase.from('organizations').select('language').eq('id',DEFAULT_ORGANIZATION_ID).maybeSingle();
    setLanguage(findLanguage(data?.language).code);
  };
  useEffect(()=>{void load();const handler=()=>void load();window.addEventListener('yasaflow-organization-settings-changed',handler);return()=>window.removeEventListener('yasaflow-organization-settings-changed',handler);},[]);
  const meta=findLanguage(language);
  useEffect(()=>{document.documentElement.lang=meta.locale;document.documentElement.dir=meta.direction;},[meta.locale,meta.direction]);
  const value=useMemo<I18nValue>(()=>({language:meta.code,direction:meta.direction,locale:meta.locale,t:(key)=>dictionaries[meta.code]?.[key]||en[key]||nb[key]||key,reload:load}),[meta.code,meta.direction,meta.locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useAppI18n(){return useContext(I18nContext);}
