import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { findLanguage } from './languageRegistry';
import { DEFAULT_ORGANIZATION_ID } from './organization';
import { supabase } from './supabase';

type Dictionary = Record<string, string>;

const nb: Dictionary = {
  'nav.home':'Hjem','nav.donation':'Donasjon','nav.contact':'Kontakt',
  'contact.title':'Kontakt','contact.subtitle':'Ta kontakt med oss','contact.location':'FYSISK ADRESSE','contact.address':'Organisasjonens adresse','contact.directions':'FINN FREM','contact.askTitle':'Still et spørsmål','contact.askSubtitle':'Send spørsmålet ditt via WhatsApp','contact.askBody':'Har du spørsmål? Kontakt organisasjonen via WhatsApp, så hjelper vi deg så snart som mulig.','contact.askButton':'SPØR VIA WHATSAPP','contact.staff':'Våre kontaktpersoner','contact.noStaff':'Ingen kontaktpersoner er registrert ennå.','contact.call':'Ring',
  'home.changeCity':'Endre by','home.searchCity':'Søk etter by...','home.useLocation':'Bruk min posisjon','home.nextPrayer':'Neste','home.loadingPrayer':'Henter bønnetider...','home.todayProgram':'Dagens program','home.upcomingActivities':'Kommende aktiviteter','home.noUpcomingActivities':'Ingen kommende aktiviteter.','home.news':'Nyheter','home.noNews':'Ingen nyheter ennå.',
  'install.title':'Installer appen','install.description':'Legg den til på startskjermen for rask tilgang','install.button':'Installer','install.close':'Lukk',
  'common.loading':'Laster...','common.close':'Lukk','common.save':'Lagre','common.saving':'Lagrer...',
  'recovery.title':'Velg nytt passord','recovery.password':'Nytt passord','recovery.repeat':'Gjenta nytt passord','recovery.show':'Vis passord','recovery.tooShort':'Passordet må ha minst 6 tegn.','recovery.noMatch':'Passordene er ikke like.','recovery.noConnection':'Ingen forbindelse til systemet.','recovery.failed':'Passordet kunne ikke lagres: ','recovery.success':'Passordet er lagret. Du kan nå logge inn med det nye passordet.',
  'login.title':'Administratorinnlogging','login.email':'E-post','login.password':'Passord','login.submit':'Logg inn','login.invalid':'Feil e-post eller passord.','login.forgotPassword':'Glemt passord?','login.temporaryPassword':'Du har logget inn med et midlertidig passord. Velg et permanent passord før du fortsetter.','login.showPasswords':'Vis passordene','login.savePassword':'Lagre nytt passord','login.passwordUpdateFailed':'Passordet kunne ikke oppdateres: ',
  'forgot.title':'Tilbakestill passord','forgot.description':'Skriv inn e-postadressen din. Du får tilsendt en sikker lenke for å velge nytt passord.','forgot.emailRequired':'E-post er obligatorisk.','forgot.sendFailed':'E-posten kunne ikke sendes: ','forgot.sent':'En lenke for tilbakestilling er sendt til e-postadressen din.','forgot.submit':'Send tilbakestillingslenke',
  'installGuide.title':'Installer appen','installGuide.subtitle':'Legg appen til på startskjermen','installGuide.iosShareTitle':'Trykk på Del','installGuide.iosShareBody':'Trykk på Del-knappen nederst i Safari.','installGuide.share':'Del','installGuide.bottomOfScreen':'Nederst på skjermen','installGuide.addHomeTitle':'Velg Legg til på Hjem-skjerm','installGuide.iosAddHomeBody':'Rull ned i menyen og trykk på «Legg til på Hjem-skjerm».','installGuide.addHome':'Legg til på Hjem-skjerm','installGuide.doneTitle':'Ferdig!','installGuide.doneBody':'Appikonet vises nå på startskjermen, og appen kan åpnes direkte derfra.','installGuide.openMenuTitle':'Åpne nettlesermenyen','installGuide.samsungMenuBody':'Trykk på menyikonet i Samsung Internet.','installGuide.topRight':'Øverst til høyre','installGuide.menu':'Meny','installGuide.samsungAddHomeBody':'Velg «Legg til side på» og deretter startskjermen.','installGuide.browserMenu':'Nettlesermeny','installGuide.genericBody':'Åpne nettlesermenyen og velg «Legg til på startskjermen» eller «Installer app».','installGuide.doneShort':'Appikonet vises nå på startskjermen.','installGuide.understood':'Forstått',
  'activity.label':'Aktivitet','activity.contact':'Kontaktperson','activity.addCalendar':'Legg til i kalender','activity.addReminder':'Legg til påminnelse','activity.call':'Ring','activity.sms':'SMS','activity.whatsapp':'WhatsApp','activity.email':'E-post',
  'donation.title':'Støtt arbeidet vårt','donation.subtitle':'Bidraget ditt støtter organisasjonens aktiviteter og arbeid.','donation.copyNumber':'Kopier nummer','donation.copied':'Kopiert','donation.openVipps':'Åpne i Vipps','donation.openingVipps':'Åpner Vipps...','donation.vippsDisabled':'Vipps-lenken er deaktivert. Du kan kopiere nummeret for å bidra.','donation.note':'Alle bidrag brukes til organisasjonens aktiviteter, tilbud og samfunnsnyttige arbeid.'
};

const en: Dictionary = {
  'nav.home':'Home','nav.donation':'Donate','nav.contact':'Contact',
  'contact.title':'Contact','contact.subtitle':'Get in touch with us','contact.location':'PHYSICAL LOCATION','contact.address':'Organization address','contact.directions':'GET DIRECTIONS','contact.askTitle':'Ask a question','contact.askSubtitle':'Send your question via WhatsApp','contact.askBody':'Do you have a question? Contact the organization through WhatsApp and we will help as soon as possible.','contact.askButton':'ASK ON WHATSAPP','contact.staff':'Our contacts','contact.noStaff':'No contacts have been registered yet.','contact.call':'Call',
  'home.changeCity':'Change city','home.searchCity':'Search city...','home.useLocation':'Use my location','home.nextPrayer':'Next','home.loadingPrayer':'Loading prayer times...','home.todayProgram':'Today’s program','home.upcomingActivities':'Upcoming activities','home.noUpcomingActivities':'No upcoming activities.','home.news':'News','home.noNews':'No news yet.',
  'install.title':'Install the app','install.description':'Add it to your home screen for quick access','install.button':'Install','install.close':'Close',
  'common.loading':'Loading...','common.close':'Close','common.save':'Save','common.saving':'Saving...',
  'recovery.title':'Choose a new password','recovery.password':'New password','recovery.repeat':'Repeat new password','recovery.show':'Show password','recovery.tooShort':'The password must contain at least 6 characters.','recovery.noMatch':'The passwords do not match.','recovery.noConnection':'No connection to the system.','recovery.failed':'The password could not be saved: ','recovery.success':'The password has been saved. You can now sign in with the new password.',
  'login.title':'Administrator sign in','login.email':'Email','login.password':'Password','login.submit':'Sign in','login.invalid':'Incorrect email or password.','login.forgotPassword':'Forgot password?','login.temporaryPassword':'You signed in with a temporary password. Choose a permanent password before continuing.','login.showPasswords':'Show passwords','login.savePassword':'Save new password','login.passwordUpdateFailed':'The password could not be updated: ',
  'forgot.title':'Reset password','forgot.description':'Enter your email address. We will send you a secure link to choose a new password.','forgot.emailRequired':'Email is required.','forgot.sendFailed':'The reset email could not be sent: ','forgot.sent':'A password reset link has been sent to your email address.','forgot.submit':'Send reset link',
  'installGuide.title':'Install the app','installGuide.subtitle':'Add the app to your home screen','installGuide.iosShareTitle':'Tap Share','installGuide.iosShareBody':'Tap the Share button at the bottom of Safari.','installGuide.share':'Share','installGuide.bottomOfScreen':'Bottom of screen','installGuide.addHomeTitle':'Choose Add to Home Screen','installGuide.iosAddHomeBody':'Scroll down in the menu and tap “Add to Home Screen”.','installGuide.addHome':'Add to Home Screen','installGuide.doneTitle':'Done!','installGuide.doneBody':'The app icon is now on your home screen and can be opened directly from there.','installGuide.openMenuTitle':'Open the browser menu','installGuide.samsungMenuBody':'Tap the menu icon in Samsung Internet.','installGuide.topRight':'Top right','installGuide.menu':'Menu','installGuide.samsungAddHomeBody':'Choose “Add page to” and then Home screen.','installGuide.browserMenu':'Browser menu','installGuide.genericBody':'Open the browser menu and choose “Add to Home screen” or “Install app”.','installGuide.doneShort':'The app icon is now on your home screen.','installGuide.understood':'Got it',
  'activity.label':'Activity','activity.contact':'Contact person','activity.addCalendar':'Add to calendar','activity.addReminder':'Add reminder','activity.call':'Call','activity.sms':'SMS','activity.whatsapp':'WhatsApp','activity.email':'Email',
  'donation.title':'Support our work','donation.subtitle':'Your contribution supports the organization’s activities and work.','donation.copyNumber':'Copy number','donation.copied':'Copied','donation.openVipps':'Open in Vipps','donation.openingVipps':'Opening Vipps...','donation.vippsDisabled':'The Vipps link is disabled. You can copy the number to contribute.','donation.note':'All contributions support the organization’s activities, services and community work.'
};

const da: Dictionary = {
  'nav.home':'Hjem','nav.donation':'Donation','nav.contact':'Kontakt',
  'contact.title':'Kontakt','contact.subtitle':'Kontakt os','contact.location':'FYSISK ADRESSE','contact.address':'Organisationens adresse','contact.directions':'FIND VEJ','contact.askTitle':'Stil et spørgsmål','contact.askSubtitle':'Send dit spørgsmål via WhatsApp','contact.askBody':'Har du et spørgsmål? Kontakt organisationen via WhatsApp, så hjælper vi dig hurtigst muligt.','contact.askButton':'SPØRG VIA WHATSAPP','contact.staff':'Vores kontaktpersoner','contact.noStaff':'Der er endnu ikke registreret nogen kontaktpersoner.','contact.call':'Ring',
  'home.changeCity':'Skift by','home.searchCity':'Søg efter by...','home.useLocation':'Brug min placering','home.nextPrayer':'Næste','home.loadingPrayer':'Henter bedetider...','home.todayProgram':'Dagens program','home.upcomingActivities':'Kommende aktiviteter','home.noUpcomingActivities':'Ingen kommende aktiviteter.','home.news':'Nyheder','home.noNews':'Ingen nyheder endnu.',
  'install.title':'Installér appen','install.description':'Føj den til startskærmen for hurtig adgang','install.button':'Installér','install.close':'Luk',
  'common.loading':'Indlæser...','common.close':'Luk','common.save':'Gem','common.saving':'Gemmer...',
  'recovery.title':'Vælg en ny adgangskode','recovery.password':'Ny adgangskode','recovery.repeat':'Gentag ny adgangskode','recovery.show':'Vis adgangskode','recovery.tooShort':'Adgangskoden skal være på mindst 6 tegn.','recovery.noMatch':'Adgangskoderne er ikke ens.','recovery.noConnection':'Ingen forbindelse til systemet.','recovery.failed':'Adgangskoden kunne ikke gemmes: ','recovery.success':'Adgangskoden er gemt. Du kan nu logge ind med den nye adgangskode.',
  'login.title':'Administratorlogin','login.email':'E-mail','login.password':'Adgangskode','login.submit':'Log ind','login.invalid':'Forkert e-mail eller adgangskode.','login.forgotPassword':'Glemt adgangskode?','login.temporaryPassword':'Du er logget ind med en midlertidig adgangskode. Vælg en permanent adgangskode, før du fortsætter.','login.showPasswords':'Vis adgangskoder','login.savePassword':'Gem ny adgangskode','login.passwordUpdateFailed':'Adgangskoden kunne ikke opdateres: ',
  'forgot.title':'Nulstil adgangskode','forgot.description':'Indtast din e-mailadresse. Du modtager et sikkert link til at vælge en ny adgangskode.','forgot.emailRequired':'E-mail er påkrævet.','forgot.sendFailed':'E-mailen kunne ikke sendes: ','forgot.sent':'Et link til nulstilling er sendt til din e-mailadresse.','forgot.submit':'Send nulstillingslink',
  'installGuide.title':'Installér appen','installGuide.subtitle':'Føj appen til startskærmen','installGuide.iosShareTitle':'Tryk på Del','installGuide.iosShareBody':'Tryk på Del-knappen nederst i Safari.','installGuide.share':'Del','installGuide.bottomOfScreen':'Nederst på skærmen','installGuide.addHomeTitle':'Vælg Føj til hjemmeskærm','installGuide.iosAddHomeBody':'Rul ned i menuen, og tryk på “Føj til hjemmeskærm”.','installGuide.addHome':'Føj til hjemmeskærm','installGuide.doneTitle':'Færdig!','installGuide.doneBody':'Appikonet vises nu på startskærmen, og appen kan åbnes direkte derfra.','installGuide.openMenuTitle':'Åbn browsermenuen','installGuide.samsungMenuBody':'Tryk på menuikonet i Samsung Internet.','installGuide.topRight':'Øverst til højre','installGuide.menu':'Menu','installGuide.samsungAddHomeBody':'Vælg “Føj side til” og derefter startskærmen.','installGuide.browserMenu':'Browsermenu','installGuide.genericBody':'Åbn browsermenuen, og vælg “Føj til startskærm” eller “Installér app”.','installGuide.doneShort':'Appikonet vises nu på startskærmen.','installGuide.understood':'Forstået',
  'activity.label':'Aktivitet','activity.contact':'Kontaktperson','activity.addCalendar':'Føj til kalender','activity.addReminder':'Tilføj påmindelse','activity.call':'Ring','activity.sms':'SMS','activity.whatsapp':'WhatsApp','activity.email':'E-mail',
  'donation.title':'Støt vores arbejde','donation.subtitle':'Dit bidrag støtter organisationens aktiviteter og arbejde.','donation.copyNumber':'Kopiér nummer','donation.copied':'Kopieret','donation.openVipps':'Åbn i Vipps','donation.openingVipps':'Åbner Vipps...','donation.vippsDisabled':'Vipps-linket er deaktiveret. Du kan kopiere nummeret for at bidrage.','donation.note':'Alle bidrag bruges til organisationens aktiviteter, tilbud og samfundsnyttige arbejde.'
};

const tr: Dictionary = { ...en, 'nav.home':'Ana Sayfa','nav.donation':'Bağış','nav.contact':'İletişim','home.news':'Haberler','home.noNews':'Henüz haber yok.','common.loading':'Yükleniyor...','common.close':'Kapat','common.save':'Kaydet','common.saving':'Kaydediliyor...','login.title':'Yönetici Girişi','login.email':'E-posta','login.password':'Şifre','login.submit':'Giriş Yap','forgot.title':'Şifreyi Sıfırla','donation.title':'Çalışmalarımızı Destekleyin' };
const ar: Dictionary = { ...en, 'nav.home':'الرئيسية','nav.donation':'تبرع','nav.contact':'اتصل بنا','home.news':'الأخبار','common.loading':'جارٍ التحميل...','common.close':'إغلاق','common.save':'حفظ','login.title':'تسجيل دخول المسؤول','donation.title':'ادعم عملنا' };
const ur: Dictionary = { ...en, 'nav.home':'ہوم','nav.donation':'عطیہ','nav.contact':'رابطہ','home.news':'خبریں','common.loading':'لوڈ ہو رہا ہے...','common.close':'بند کریں','common.save':'محفوظ کریں','login.title':'ایڈمن لاگ اِن','donation.title':'ہمارے کام کی حمایت کریں' };

const dictionaries: Record<string, Dictionary> = { nb, en, da, tr, ar, ur };

type I18nValue = { language:string; direction:'ltr'|'rtl'; locale:string; t:(key:string)=>string; reload:()=>Promise<void> };
const I18nContext = createContext<I18nValue>({ language:'nb', direction:'ltr', locale:'nb-NO', t:(key)=>nb[key]||key, reload:async()=>{} });

export function AppI18nProvider({ children }: { children: ReactNode }) {
  const [language,setLanguage]=useState('nb');
  const load=async()=>{
    if(!supabase)return;
    const {data}=await supabase.from('organizations').select('language').eq('id',DEFAULT_ORGANIZATION_ID).maybeSingle();
    setLanguage(findLanguage(data?.language).code);
  };
  useEffect(()=>{void load();const handler=()=>void load();window.addEventListener('yasaflow-organization-settings-changed',handler);return()=>window.removeEventListener('yasaflow-organization-settings-changed',handler);},[]);
  const meta=findLanguage(language);
  useEffect(()=>{document.documentElement.lang=meta.locale;document.documentElement.dir=meta.direction;},[meta.locale,meta.direction]);
  const value=useMemo<I18nValue>(()=>({language:meta.code,direction:meta.direction,locale:meta.locale,t:(key)=>dictionaries[meta.code]?.[key]||en[key]||nb[key]||key,reload:load}),[meta.code,meta.direction,meta.locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useAppI18n(){return useContext(I18nContext);}
