type Dictionary = Record<string, string>;

const nb: Dictionary = {
  'members.unnamed':'Uten navn','members.supabaseMissing':'Supabase er ikke konfigurert.','members.migrationMissing':'Medlemstabellene er ikke klare i Supabase ennå. Kjør Members-migrasjonen i SQL Editor.','members.nameRequired':'Navn er obligatorisk.','members.personCreateFailed':'Personen kunne ikke opprettes.','members.saveFailed':'Medlemmet kunne ikke lagres.','members.numberInUse':'Medlemsnummeret er allerede i bruk i denne organisasjonen.',
  'members.coreModule':'Kjernemodul','members.title':'Medlemmer','members.registeredSuffix':'registrerte medlemskap i organisasjonen.','members.add':'Legg til medlem','members.search':'Søk navn, e-post, telefon eller medlemsnummer','members.allStatuses':'Alle statuser','members.activePlural':'Aktive','members.inactivePlural':'Inaktive','members.loading':'Henter medlemmer...','members.loadFailedTitle':'Medlemsmodulen kan ikke laste data','members.emptyTitle':'Ingen medlemmer funnet','members.emptyBody':'Legg til det første medlemmet eller endre søk/filter.','members.active':'Aktiv','members.inactive':'Inaktiv','members.noNumber':'Uten medlemsnummer','members.noContact':'Ingen kontaktinfo',
  'members.edit':'Rediger medlem','members.fullName':'Fullt navn','members.memberNumber':'Medlemsnummer','members.status':'Status','members.email':'E-post','members.phone':'Telefon','members.address':'Adresse','members.joinDate':'Innmeldingsdato','members.internalRole':'Intern rolle','members.rolePlaceholder':'F.eks. frivillig','members.internalNotes':'Interne notater','members.saving':'Lagrer...','members.saveChanges':'Lagre endringer','members.create':'Opprett medlem','members.close':'Lukk'
};
const en: Dictionary = {
  'members.unnamed':'Unnamed','members.supabaseMissing':'Supabase is not configured.','members.migrationMissing':'The member tables are not ready in Supabase. Run the Members migration in the SQL Editor.','members.nameRequired':'Name is required.','members.personCreateFailed':'The person could not be created.','members.saveFailed':'The member could not be saved.','members.numberInUse':'This membership number is already in use in the organization.',
  'members.coreModule':'Core module','members.title':'Members','members.registeredSuffix':'registered memberships in the organization.','members.add':'Add member','members.search':'Search name, email, phone or membership number','members.allStatuses':'All statuses','members.activePlural':'Active','members.inactivePlural':'Inactive','members.loading':'Loading members...','members.loadFailedTitle':'The member module cannot load data','members.emptyTitle':'No members found','members.emptyBody':'Add the first member or change the search/filter.','members.active':'Active','members.inactive':'Inactive','members.noNumber':'No membership number','members.noContact':'No contact information',
  'members.edit':'Edit member','members.fullName':'Full name','members.memberNumber':'Membership number','members.status':'Status','members.email':'Email','members.phone':'Phone','members.address':'Address','members.joinDate':'Join date','members.internalRole':'Internal role','members.rolePlaceholder':'For example volunteer','members.internalNotes':'Internal notes','members.saving':'Saving...','members.saveChanges':'Save changes','members.create':'Create member','members.close':'Close'
};
const tr: Dictionary = {
  'members.unnamed':'İsimsiz','members.supabaseMissing':'Supabase yapılandırılmamış.','members.migrationMissing':'Üye tabloları Supabase’de henüz hazır değil. SQL Editor’da Members migration dosyasını çalıştırın.','members.nameRequired':'Ad zorunludur.','members.personCreateFailed':'Kişi oluşturulamadı.','members.saveFailed':'Üye kaydedilemedi.','members.numberInUse':'Bu üye numarası kuruluşta zaten kullanılıyor.',
  'members.coreModule':'Temel modül','members.title':'Üyeler','members.registeredSuffix':'kayıtlı üyelik.','members.add':'Üye ekle','members.search':'Ad, e-posta, telefon veya üye numarası ara','members.allStatuses':'Tüm durumlar','members.activePlural':'Aktif','members.inactivePlural':'Pasif','members.loading':'Üyeler yükleniyor...','members.loadFailedTitle':'Üye modülü verileri yükleyemiyor','members.emptyTitle':'Üye bulunamadı','members.emptyBody':'İlk üyeyi ekleyin veya arama/filtreyi değiştirin.','members.active':'Aktif','members.inactive':'Pasif','members.noNumber':'Üye numarası yok','members.noContact':'İletişim bilgisi yok',
  'members.edit':'Üyeyi düzenle','members.fullName':'Ad soyad','members.memberNumber':'Üye numarası','members.status':'Durum','members.email':'E-posta','members.phone':'Telefon','members.address':'Adres','members.joinDate':'Katılım tarihi','members.internalRole':'Dahili rol','members.rolePlaceholder':'Örn. gönüllü','members.internalNotes':'Dahili notlar','members.saving':'Kaydediliyor...','members.saveChanges':'Değişiklikleri kaydet','members.create':'Üye oluştur','members.close':'Kapat'
};
const ar: Dictionary = {
  'members.unnamed':'بدون اسم','members.supabaseMissing':'لم يتم إعداد Supabase.','members.migrationMissing':'جداول الأعضاء غير جاهزة في Supabase. شغّل ترحيل Members في محرر SQL.','members.nameRequired':'الاسم مطلوب.','members.personCreateFailed':'تعذر إنشاء الشخص.','members.saveFailed':'تعذر حفظ العضو.','members.numberInUse':'رقم العضوية مستخدم بالفعل في هذه المؤسسة.',
  'members.coreModule':'وحدة أساسية','members.title':'الأعضاء','members.registeredSuffix':'عضويات مسجلة في المؤسسة.','members.add':'إضافة عضو','members.search':'البحث بالاسم أو البريد أو الهاتف أو رقم العضوية','members.allStatuses':'كل الحالات','members.activePlural':'نشطون','members.inactivePlural':'غير نشطين','members.loading':'جارٍ تحميل الأعضاء...','members.loadFailedTitle':'تعذر تحميل بيانات وحدة الأعضاء','members.emptyTitle':'لم يتم العثور على أعضاء','members.emptyBody':'أضف العضو الأول أو غيّر البحث أو الفلتر.','members.active':'نشط','members.inactive':'غير نشط','members.noNumber':'بدون رقم عضوية','members.noContact':'لا توجد معلومات اتصال',
  'members.edit':'تعديل العضو','members.fullName':'الاسم الكامل','members.memberNumber':'رقم العضوية','members.status':'الحالة','members.email':'البريد الإلكتروني','members.phone':'الهاتف','members.address':'العنوان','members.joinDate':'تاريخ الانضمام','members.internalRole':'الدور الداخلي','members.rolePlaceholder':'مثلاً متطوع','members.internalNotes':'ملاحظات داخلية','members.saving':'جارٍ الحفظ...','members.saveChanges':'حفظ التغييرات','members.create':'إنشاء عضو','members.close':'إغلاق'
};
const ur: Dictionary = {
  'members.unnamed':'بغیر نام','members.supabaseMissing':'Supabase ترتیب نہیں دیا گیا۔','members.migrationMissing':'ارکان کی جدولیں Supabase میں تیار نہیں۔ SQL Editor میں Members migration چلائیں۔','members.nameRequired':'نام ضروری ہے۔','members.personCreateFailed':'شخص نہیں بنایا جا سکا۔','members.saveFailed':'رکن محفوظ نہیں ہو سکا۔','members.numberInUse':'یہ رکنیت نمبر تنظیم میں پہلے سے استعمال ہو رہا ہے۔',
  'members.coreModule':'بنیادی ماڈیول','members.title':'ارکان','members.registeredSuffix':'رجسٹرڈ رکنیتیں۔','members.add':'رکن شامل کریں','members.search':'نام، ای میل، فون یا رکنیت نمبر تلاش کریں','members.allStatuses':'تمام حالتیں','members.activePlural':'فعال','members.inactivePlural':'غیر فعال','members.loading':'ارکان لوڈ ہو رہے ہیں...','members.loadFailedTitle':'ارکان کا ماڈیول ڈیٹا لوڈ نہیں کر سکا','members.emptyTitle':'کوئی رکن نہیں ملا','members.emptyBody':'پہلا رکن شامل کریں یا تلاش/فلٹر تبدیل کریں۔','members.active':'فعال','members.inactive':'غیر فعال','members.noNumber':'رکنیت نمبر نہیں','members.noContact':'رابطے کی معلومات نہیں',
  'members.edit':'رکن میں ترمیم','members.fullName':'پورا نام','members.memberNumber':'رکنیت نمبر','members.status':'حالت','members.email':'ای میل','members.phone':'فون','members.address':'پتہ','members.joinDate':'شمولیت کی تاریخ','members.internalRole':'اندرونی کردار','members.rolePlaceholder':'مثلاً رضاکار','members.internalNotes':'اندرونی نوٹس','members.saving':'محفوظ ہو رہا ہے...','members.saveChanges':'تبدیلیاں محفوظ کریں','members.create':'رکن بنائیں','members.close':'بند کریں'
};

const dictionaries: Record<string, Dictionary> = { nb, en, tr, ar, ur };
export function getMemberTranslation(language: string, key: string) {
  return dictionaries[language]?.[key] || en[key] || nb[key] || key;
}
