type Dictionary = Record<string, string>;

const nb: Dictionary = {
  'public.loading':'Henter organisasjonen...','public.loadError':'Den offentlige organisasjonssiden kunne ikke lastes.','public.about':'Om organisasjonen','public.follow':'Følg oss','public.website':'Nettside','public.contact':'Kontakt','public.openingHours':'Åpningstider','public.weeklyEvent':'Ukentlig arrangement','public.news':'Nyheter','public.noNews':'Ingen offentlige nyheter er publisert ennå.','public.activities':'Kommende aktiviteter','public.noActivities':'Ingen offentlige aktiviteter er planlagt.','public.team':'Styret og kontaktpersoner','public.noTeam':'Ingen offentlige kontaktpersoner er lagt til.','public.donate':'Støtt organisasjonen','public.donateNumber':'Donasjonsnummer','public.bankAccount':'Bankkonto','public.openDonation':'Åpne donasjon','public.map':'Åpne kart','public.email':'Send e-post','public.call':'Ring','public.published':'Publisert','public.location':'Sted','public.readMore':'Les mer','public.noDescription':'Ingen beskrivelse er lagt til.','public.close':'Lukk','public.share':'Del','public.shared':'Lenken er kopiert.','public.shareFailed':'Kunne ikke dele innholdet.','public.searchEvents':'Søk arrangementer','public.allCategories':'Alle kategorier','public.availablePrefix':'ledige av','public.exportCalendar':'Eksporter til kalender','public.register':'Meld på','public.registration':'Påmelding','public.name':'Navn','public.phone':'Telefon','public.attendees':'Antall deltakere','public.confirmRegistration':'Bekreft påmelding','public.saving':'Lagrer...','public.waitlist':'Arrangementet er fullt. Du er satt på venteliste.','public.registered':'Påmeldingen er registrert.','public.eventDetails':'Aktivitetsdetaljer','public.prayerLabel':'Bønnetider','public.prayerTitle':'Dagens bønnetider','public.prayerDescription':'Bønnetidsmodulen er aktiv og vises øverst på forsiden.'
};
const en: Dictionary = {
  'public.loading':'Loading the organization...','public.loadError':'The public organization page could not be loaded.','public.about':'About the organization','public.follow':'Follow us','public.website':'Website','public.contact':'Contact','public.openingHours':'Opening hours','public.weeklyEvent':'Weekly event','public.news':'News','public.noNews':'No public news has been published yet.','public.activities':'Upcoming activities','public.noActivities':'No public activities are planned.','public.team':'Board and contacts','public.noTeam':'No public contacts have been added.','public.donate':'Support the organization','public.donateNumber':'Donation number','public.bankAccount':'Bank account','public.openDonation':'Open donation','public.map':'Open map','public.email':'Send email','public.call':'Call','public.published':'Published','public.location':'Location','public.readMore':'Read more','public.noDescription':'No description has been added.','public.close':'Close','public.share':'Share','public.shared':'The link has been copied.','public.shareFailed':'The content could not be shared.','public.searchEvents':'Search events','public.allCategories':'All categories','public.availablePrefix':'available of','public.exportCalendar':'Export to calendar','public.register':'Register','public.registration':'Registration','public.name':'Name','public.phone':'Phone','public.attendees':'Number of attendees','public.confirmRegistration':'Confirm registration','public.saving':'Saving...','public.waitlist':'The event is full. You have been placed on the waiting list.','public.registered':'Your registration has been recorded.','public.eventDetails':'Activity details','public.prayerLabel':'Prayer times','public.prayerTitle':'Today’s prayer times','public.prayerDescription':'The prayer-times module is active and appears at the top of the home page.'
};
const da: Dictionary = {
  'public.loading':'Henter organisationen...','public.loadError':'Organisationens offentlige side kunne ikke indlæses.','public.about':'Om organisationen','public.follow':'Følg os','public.website':'Hjemmeside','public.contact':'Kontakt','public.openingHours':'Åbningstider','public.weeklyEvent':'Ugentligt arrangement','public.news':'Nyheder','public.noNews':'Der er endnu ikke offentliggjort nogen offentlige nyheder.','public.activities':'Kommende aktiviteter','public.noActivities':'Der er ingen planlagte offentlige aktiviteter.','public.team':'Bestyrelse og kontaktpersoner','public.noTeam':'Der er ikke tilføjet nogen offentlige kontaktpersoner.','public.donate':'Støt organisationen','public.donateNumber':'Donationsnummer','public.bankAccount':'Bankkonto','public.openDonation':'Åbn donation','public.map':'Åbn kort','public.email':'Send e-mail','public.call':'Ring','public.published':'Udgivet','public.location':'Sted','public.readMore':'Læs mere','public.noDescription':'Der er ikke tilføjet nogen beskrivelse.','public.close':'Luk','public.share':'Del','public.shared':'Linket er kopieret.','public.shareFailed':'Indholdet kunne ikke deles.','public.searchEvents':'Søg efter arrangementer','public.allCategories':'Alle kategorier','public.availablePrefix':'ledige ud af','public.exportCalendar':'Eksportér til kalender','public.register':'Tilmeld','public.registration':'Tilmelding','public.name':'Navn','public.phone':'Telefon','public.attendees':'Antal deltagere','public.confirmRegistration':'Bekræft tilmelding','public.saving':'Gemmer...','public.waitlist':'Arrangementet er fuldt. Du er sat på venteliste.','public.registered':'Din tilmelding er registreret.','public.eventDetails':'Aktivitetsdetaljer','public.prayerLabel':'Bedetider','public.prayerTitle':'Dagens bedetider','public.prayerDescription':'Bedetidsmodulet er aktivt og vises øverst på forsiden.'
};
const tr: Dictionary = {
  'public.loading':'Kuruluş yükleniyor...','public.loadError':'Kuruluşun herkese açık sayfası yüklenemedi.','public.about':'Kuruluş hakkında','public.follow':'Bizi takip edin','public.website':'Web sitesi','public.contact':'İletişim','public.openingHours':'Çalışma saatleri','public.weeklyEvent':'Haftalık etkinlik','public.news':'Haberler','public.noNews':'Henüz herkese açık haber yayınlanmadı.','public.activities':'Yaklaşan etkinlikler','public.noActivities':'Planlanmış herkese açık etkinlik yok.','public.team':'Yönetim kurulu ve iletişim kişileri','public.noTeam':'Herkese açık iletişim kişisi eklenmedi.','public.donate':'Kuruluşu destekleyin','public.donateNumber':'Bağış numarası','public.bankAccount':'Banka hesabı','public.openDonation':'Bağışı aç','public.map':'Haritayı aç','public.email':'E-posta gönder','public.call':'Ara','public.published':'Yayınlandı','public.location':'Konum','public.readMore':'Devamını oku','public.noDescription':'Açıklama eklenmedi.','public.close':'Kapat','public.share':'Paylaş','public.shared':'Bağlantı kopyalandı.','public.shareFailed':'İçerik paylaşılamadı.','public.searchEvents':'Etkinlik ara','public.allCategories':'Tüm kategoriler','public.availablePrefix':'boş yer /','public.exportCalendar':'Takvime aktar','public.register':'Kayıt ol','public.registration':'Kayıt','public.name':'Ad','public.phone':'Telefon','public.attendees':'Katılımcı sayısı','public.confirmRegistration':'Kaydı onayla','public.saving':'Kaydediliyor...','public.waitlist':'Etkinlik dolu. Bekleme listesine eklendiniz.','public.registered':'Kaydınız alındı.','public.eventDetails':'Etkinlik ayrıntıları','public.prayerLabel':'Namaz vakitleri','public.prayerTitle':'Bugünün namaz vakitleri','public.prayerDescription':'Namaz vakitleri modülü etkin ve ana sayfanın üst kısmında gösteriliyor.'
};
const ar: Dictionary = {
  'public.loading':'جارٍ تحميل المؤسسة...','public.loadError':'تعذر تحميل الصفحة العامة للمؤسسة.','public.about':'عن المؤسسة','public.follow':'تابعنا','public.website':'الموقع الإلكتروني','public.contact':'الاتصال','public.openingHours':'ساعات العمل','public.weeklyEvent':'الفعالية الأسبوعية','public.news':'الأخبار','public.noNews':'لم يتم نشر أخبار عامة بعد.','public.activities':'الأنشطة القادمة','public.noActivities':'لا توجد أنشطة عامة مخططة.','public.team':'مجلس الإدارة وجهات الاتصال','public.noTeam':'لم تتم إضافة جهات اتصال عامة.','public.donate':'ادعم المؤسسة','public.donateNumber':'رقم التبرع','public.bankAccount':'الحساب البنكي','public.openDonation':'فتح التبرع','public.map':'فتح الخريطة','public.email':'إرسال بريد','public.call':'اتصال','public.published':'منشور','public.location':'الموقع','public.readMore':'اقرأ المزيد','public.noDescription':'لم تتم إضافة وصف.','public.close':'إغلاق','public.share':'مشاركة','public.shared':'تم نسخ الرابط.','public.shareFailed':'تعذرت مشاركة المحتوى.','public.searchEvents':'البحث عن فعالية','public.allCategories':'كل الفئات','public.availablePrefix':'أماكن متاحة من','public.exportCalendar':'تصدير إلى التقويم','public.register':'تسجيل','public.registration':'التسجيل','public.name':'الاسم','public.phone':'الهاتف','public.attendees':'عدد الحضور','public.confirmRegistration':'تأكيد التسجيل','public.saving':'جارٍ الحفظ...','public.waitlist':'الفعالية ممتلئة. تمت إضافتك إلى قائمة الانتظار.','public.registered':'تم تسجيلك.','public.eventDetails':'تفاصيل النشاط','public.prayerLabel':'مواقيت الصلاة','public.prayerTitle':'مواقيت الصلاة اليوم','public.prayerDescription':'وحدة مواقيت الصلاة مفعلة وتظهر أعلى الصفحة الرئيسية.'
};
const ur: Dictionary = {
  'public.loading':'تنظیم لوڈ ہو رہی ہے...','public.loadError':'تنظیم کا عوامی صفحہ لوڈ نہیں ہو سکا۔','public.about':'تنظیم کے بارے میں','public.follow':'ہمیں فالو کریں','public.website':'ویب سائٹ','public.contact':'رابطہ','public.openingHours':'اوقات کار','public.weeklyEvent':'ہفتہ وار پروگرام','public.news':'خبریں','public.noNews':'ابھی کوئی عوامی خبر شائع نہیں ہوئی۔','public.activities':'آنے والی سرگرمیاں','public.noActivities':'کوئی عوامی سرگرمی طے نہیں۔','public.team':'بورڈ اور رابطہ افراد','public.noTeam':'کوئی عوامی رابطہ شخص شامل نہیں۔','public.donate':'تنظیم کی مدد کریں','public.donateNumber':'عطیہ نمبر','public.bankAccount':'بینک اکاؤنٹ','public.openDonation':'عطیہ کھولیں','public.map':'نقشہ کھولیں','public.email':'ای میل بھیجیں','public.call':'کال','public.published':'شائع شدہ','public.location':'مقام','public.readMore':'مزید پڑھیں','public.noDescription':'کوئی تفصیل شامل نہیں۔','public.close':'بند کریں','public.share':'شیئر','public.shared':'لنک کاپی ہو گیا۔','public.shareFailed':'مواد شیئر نہیں ہو سکا۔','public.searchEvents':'پروگرام تلاش کریں','public.allCategories':'تمام زمرے','public.availablePrefix':'خالی جگہیں از','public.exportCalendar':'کیلنڈر میں شامل کریں','public.register':'رجسٹر کریں','public.registration':'رجسٹریشن','public.name':'نام','public.phone':'فون','public.attendees':'شرکاء کی تعداد','public.confirmRegistration':'رجسٹریشن کی تصدیق','public.saving':'محفوظ ہو رہا ہے...','public.waitlist':'پروگرام مکمل ہے۔ آپ کو انتظار کی فہرست میں شامل کیا گیا ہے۔','public.registered':'آپ کی رجسٹریشن ہو گئی ہے۔','public.eventDetails':'سرگرمی کی تفصیلات','public.prayerLabel':'نماز کے اوقات','public.prayerTitle':'آج کے نماز کے اوقات','public.prayerDescription':'نماز کے اوقات کا ماڈیول فعال ہے اور ہوم پیج کے اوپر دکھایا جاتا ہے۔'
};

const dictionaries: Record<string, Dictionary> = { nb, en, da, tr, ar, ur };
export function getPublicOrganizationTranslation(language: string, key: string) {
  return dictionaries[language]?.[key] || en[key] || nb[key] || key;
}
