type Dictionary = Record<string, string>;

const nb: Dictionary = {
  'settings.saved':'Innstillingene er lagret. Språket oppdateres i appen.','settings.title':'Organisasjonsinnstillinger','settings.subtitle':'Kontakt, profil, språk, donasjon og valgfrie moduler.','settings.appLanguage':'Appspråk','settings.languageHelp':'Søk etter språk i stedet for å bla gjennom hele listen.','settings.searchLanguage':'Søk: norsk, urdu, arabisk, tysk...','settings.noLanguage':'Ingen språk funnet.','settings.languageNote':'Nye språk kan legges til sentralt uten å bygge om denne menyen.','settings.displayName':'Visningsnavn','settings.shortName':'Kort navn','settings.description':'Organisasjonsbeskrivelse','settings.bannerUrl':'Banner-URL','settings.website':'Nettside','settings.facebook':'Facebook-lenke','settings.instagram':'Instagram-lenke','settings.youtube':'YouTube-lenke','settings.tiktok':'TikTok-lenke','settings.phone':'Telefon','settings.email':'E-post','settings.whatsapp':'WhatsApp','settings.address':'Adresse','settings.mapUrl':'Kartlenke','settings.logoUrl':'Logo-URL','settings.appIconUrl':'Appikon-URL','settings.donationNumber':'Donasjonsnummer','settings.donationUrl':'Donasjonslenke','settings.bankAccount':'Bankkonto','settings.iban':'IBAN','settings.openingHours':'Åpningstider','settings.weeklyEvent':'Ukentlig arrangement','settings.optionalModules':'Valgfrie moduler','settings.dailyTitle':'Dagens vers og hadith','settings.dailyBody':'Vis et daglig vers og en hadith på forsiden. Passer for moskeer og islamske organisasjoner, men er valgfritt.','settings.enableRamadan':'Aktiver Ramadan','settings.enableKurban':'Aktiver Kurban','settings.startDate':'Startdato','settings.endDate':'Sluttdato','settings.save':'Lagre innstillinger','settings.active':'Aktiv','settings.off':'Av','settings.publicTitle':'Offentlige innstillinger','settings.publicSubtitle':'Vis kun det organisasjonen har valgt å publisere.','settings.publicVisible':'Vis dette offentlig i appen.','settings.fillFirst':'Fyll inn feltet først.'
};
const en: Dictionary = {
  'settings.saved':'Settings have been saved. The app language is being updated.','settings.title':'Organization settings','settings.subtitle':'Contact details, profile, language, donations and optional modules.','settings.appLanguage':'App language','settings.languageHelp':'Search for a language instead of browsing the full list.','settings.searchLanguage':'Search: Norwegian, Urdu, Arabic, German...','settings.noLanguage':'No languages found.','settings.languageNote':'New languages can be added centrally without rebuilding this menu.','settings.displayName':'Display name','settings.shortName':'Short name','settings.description':'Organization description','settings.bannerUrl':'Banner URL','settings.website':'Website','settings.facebook':'Facebook link','settings.instagram':'Instagram link','settings.youtube':'YouTube link','settings.tiktok':'TikTok link','settings.phone':'Phone','settings.email':'Email','settings.whatsapp':'WhatsApp','settings.address':'Address','settings.mapUrl':'Map link','settings.logoUrl':'Logo URL','settings.appIconUrl':'App icon URL','settings.donationNumber':'Donation number','settings.donationUrl':'Donation link','settings.bankAccount':'Bank account','settings.iban':'IBAN','settings.openingHours':'Opening hours','settings.weeklyEvent':'Weekly event','settings.optionalModules':'Optional modules','settings.dailyTitle':'Daily verse and hadith','settings.dailyBody':'Show a daily verse and hadith on the home page. Suitable for mosques and Islamic organizations, but optional.','settings.enableRamadan':'Enable Ramadan','settings.enableKurban':'Enable Qurbani','settings.startDate':'Start date','settings.endDate':'End date','settings.save':'Save settings','settings.active':'Active','settings.off':'Off','settings.publicTitle':'Public settings','settings.publicSubtitle':'Only show information the organization has chosen to publish.','settings.publicVisible':'Show this publicly in the app.','settings.fillFirst':'Complete the field first.'
};
const tr: Dictionary = {
  'settings.saved':'Ayarlar kaydedildi. Uygulama dili güncelleniyor.','settings.title':'Kuruluş ayarları','settings.subtitle':'İletişim, profil, dil, bağış ve isteğe bağlı modüller.','settings.appLanguage':'Uygulama dili','settings.languageHelp':'Tüm listeyi gezmek yerine dil arayın.','settings.searchLanguage':'Ara: Norveççe, Urduca, Arapça, Almanca...','settings.noLanguage':'Dil bulunamadı.','settings.languageNote':'Yeni diller bu menü yeniden oluşturulmadan merkezi olarak eklenebilir.','settings.displayName':'Görünen ad','settings.shortName':'Kısa ad','settings.description':'Kuruluş açıklaması','settings.bannerUrl':'Banner URL','settings.website':'Web sitesi','settings.facebook':'Facebook bağlantısı','settings.instagram':'Instagram bağlantısı','settings.youtube':'YouTube bağlantısı','settings.tiktok':'TikTok bağlantısı','settings.phone':'Telefon','settings.email':'E-posta','settings.whatsapp':'WhatsApp','settings.address':'Adres','settings.mapUrl':'Harita bağlantısı','settings.logoUrl':'Logo URL','settings.appIconUrl':'Uygulama simgesi URL','settings.donationNumber':'Bağış numarası','settings.donationUrl':'Bağış bağlantısı','settings.bankAccount':'Banka hesabı','settings.iban':'IBAN','settings.openingHours':'Çalışma saatleri','settings.weeklyEvent':'Haftalık etkinlik','settings.optionalModules':'İsteğe bağlı modüller','settings.dailyTitle':'Günün ayeti ve hadisi','settings.dailyBody':'Ana sayfada günlük bir ayet ve hadis gösterir. Camiler ve İslami kuruluşlar için uygundur, ancak isteğe bağlıdır.','settings.enableRamadan':'Ramazanı etkinleştir','settings.enableKurban':'Kurbanı etkinleştir','settings.startDate':'Başlangıç tarihi','settings.endDate':'Bitiş tarihi','settings.save':'Ayarları kaydet','settings.active':'Aktif','settings.off':'Kapalı','settings.publicTitle':'Herkese açık ayarlar','settings.publicSubtitle':'Yalnızca kuruluşun yayınlamayı seçtiği bilgileri gösterin.','settings.publicVisible':'Bunu uygulamada herkese açık göster.','settings.fillFirst':'Önce alanı doldurun.'
};
const ar: Dictionary = {
  'settings.saved':'تم حفظ الإعدادات. جارٍ تحديث لغة التطبيق.','settings.title':'إعدادات المؤسسة','settings.subtitle':'الاتصال والملف واللغة والتبرعات والوحدات الاختيارية.','settings.appLanguage':'لغة التطبيق','settings.languageHelp':'ابحث عن اللغة بدلاً من تصفح القائمة كاملة.','settings.searchLanguage':'ابحث: النرويجية، الأردية، العربية، الألمانية...','settings.noLanguage':'لم يتم العثور على لغات.','settings.languageNote':'يمكن إضافة لغات جديدة مركزياً دون إعادة بناء هذه القائمة.','settings.displayName':'اسم العرض','settings.shortName':'الاسم المختصر','settings.description':'وصف المؤسسة','settings.bannerUrl':'رابط صورة الغلاف','settings.website':'الموقع الإلكتروني','settings.facebook':'رابط فيسبوك','settings.instagram':'رابط إنستغرام','settings.youtube':'رابط يوتيوب','settings.tiktok':'رابط تيك توك','settings.phone':'الهاتف','settings.email':'البريد الإلكتروني','settings.whatsapp':'واتساب','settings.address':'العنوان','settings.mapUrl':'رابط الخريطة','settings.logoUrl':'رابط الشعار','settings.appIconUrl':'رابط أيقونة التطبيق','settings.donationNumber':'رقم التبرع','settings.donationUrl':'رابط التبرع','settings.bankAccount':'الحساب البنكي','settings.iban':'IBAN','settings.openingHours':'ساعات العمل','settings.weeklyEvent':'الفعالية الأسبوعية','settings.optionalModules':'الوحدات الاختيارية','settings.dailyTitle':'آية وحديث اليوم','settings.dailyBody':'عرض آية وحديث يومياً في الصفحة الرئيسية. مناسب للمساجد والمؤسسات الإسلامية، لكنه اختياري.','settings.enableRamadan':'تفعيل رمضان','settings.enableKurban':'تفعيل الأضحية','settings.startDate':'تاريخ البدء','settings.endDate':'تاريخ الانتهاء','settings.save':'حفظ الإعدادات','settings.active':'نشط','settings.off':'متوقف','settings.publicTitle':'الإعدادات العامة','settings.publicSubtitle':'اعرض فقط المعلومات التي اختارت المؤسسة نشرها.','settings.publicVisible':'اعرض هذا علناً في التطبيق.','settings.fillFirst':'أكمل الحقل أولاً.'
};
const ur: Dictionary = {
  'settings.saved':'ترتیبات محفوظ ہو گئیں۔ ایپ کی زبان اپ ڈیٹ ہو رہی ہے۔','settings.title':'تنظیم کی ترتیبات','settings.subtitle':'رابطہ، پروفائل، زبان، عطیات اور اختیاری ماڈیولز۔','settings.appLanguage':'ایپ کی زبان','settings.languageHelp':'مکمل فہرست دیکھنے کے بجائے زبان تلاش کریں۔','settings.searchLanguage':'تلاش: نارویجین، اردو، عربی، جرمن...','settings.noLanguage':'کوئی زبان نہیں ملی۔','settings.languageNote':'اس مینو کو دوبارہ بنائے بغیر نئی زبانیں مرکزی طور پر شامل کی جا سکتی ہیں۔','settings.displayName':'ظاہر ہونے والا نام','settings.shortName':'مختصر نام','settings.description':'تنظیم کی تفصیل','settings.bannerUrl':'بینر URL','settings.website':'ویب سائٹ','settings.facebook':'Facebook لنک','settings.instagram':'Instagram لنک','settings.youtube':'YouTube لنک','settings.tiktok':'TikTok لنک','settings.phone':'فون','settings.email':'ای میل','settings.whatsapp':'WhatsApp','settings.address':'پتہ','settings.mapUrl':'نقشے کا لنک','settings.logoUrl':'لوگو URL','settings.appIconUrl':'ایپ آئیکن URL','settings.donationNumber':'عطیہ نمبر','settings.donationUrl':'عطیہ لنک','settings.bankAccount':'بینک اکاؤنٹ','settings.iban':'IBAN','settings.openingHours':'اوقات کار','settings.weeklyEvent':'ہفتہ وار پروگرام','settings.optionalModules':'اختیاری ماڈیولز','settings.dailyTitle':'آج کی آیت اور حدیث','settings.dailyBody':'ہوم پیج پر روزانہ ایک آیت اور حدیث دکھائیں۔ مساجد اور اسلامی تنظیموں کے لیے موزوں، مگر اختیاری۔','settings.enableRamadan':'رمضان فعال کریں','settings.enableKurban':'قربانی فعال کریں','settings.startDate':'شروع ہونے کی تاریخ','settings.endDate':'اختتام کی تاریخ','settings.save':'ترتیبات محفوظ کریں','settings.active':'فعال','settings.off':'بند','settings.publicTitle':'عوامی ترتیبات','settings.publicSubtitle':'صرف وہ معلومات دکھائیں جنہیں تنظیم نے شائع کرنے کے لیے منتخب کیا ہے۔','settings.publicVisible':'اسے ایپ میں عوامی طور پر دکھائیں۔','settings.fillFirst':'پہلے فیلڈ مکمل کریں۔'
};

const dictionaries: Record<string, Dictionary> = { nb, en, tr, ar, ur };
export function getSettingsTranslation(language: string, key: string) {
  return dictionaries[language]?.[key] || en[key] || nb[key] || key;
}
