import { useEffect,useState } from 'react';
import { BadgeCheck,Loader2,ShieldAlert } from 'lucide-react';
import { supabase } from '../lib/supabase';

type CardData={organization_id:string;organization_name:string;organization_logo_url:string|null;member_name:string;member_number:string|null;membership_status:string;card_token:string};

export function PublicMemberCardPage(){
 const token=new URLSearchParams(window.location.search).get('token')||'';
 const [card,setCard]=useState<CardData|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{let cancelled=false;(async()=>{if(!supabase||!token){setError('Medlemskortlenken er ugyldig.');setLoading(false);return;}const {data,error}=await supabase.rpc('get_public_member_card',{p_token:token});if(cancelled)return;if(error){setError(error.message);setLoading(false);return;}const row=Array.isArray(data)?data[0]:data;if(!row){setError('Medlemskortet finnes ikke eller er ikke aktivt.');setLoading(false);return;}setCard(row as CardData);setLoading(false);})();return()=>{cancelled=true;};},[token]);
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-slate-50"><Loader2 className="animate-spin text-blue-600" size={30}/></div>;
 if(!card)return <main className="flex min-h-screen items-center justify-center bg-slate-50 p-4"><section className="w-full max-w-md rounded-3xl border bg-white p-7 text-center shadow-sm"><ShieldAlert className="mx-auto text-red-500" size={34}/><h1 className="mt-4 text-xl font-semibold">Kan ikke åpne medlemskortet</h1><p className="mt-2 text-sm text-slate-500">{error}</p></section></main>;
 const qrValue=`yasaflow-member:${card.organization_id}:${card.card_token}`;
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-8"><section className="mx-auto w-full max-w-sm rounded-[2rem] border bg-white p-6 text-center shadow-xl"><div className="mx-auto flex h-16 w-16 items-center justify-center overflow-hidden rounded-2xl bg-blue-50">{card.organization_logo_url?<img src={card.organization_logo_url} alt="" className="h-full w-full object-cover"/>:<BadgeCheck className="text-blue-600" size={34}/>}</div><p className="mt-4 text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">Digitalt medlemskort</p><h1 className="mt-2 text-2xl font-bold text-slate-900">{card.member_name}</h1><p className="mt-1 text-sm text-slate-500">{card.organization_name}</p><div className="mt-5 rounded-2xl bg-slate-50 px-4 py-3"><p className="text-[11px] uppercase tracking-wider text-slate-400">Medlemsnummer</p><p className="mt-1 font-semibold text-slate-800">{card.member_number||'Medlem'}</p></div><img src={`https://quickchart.io/qr?size=260&text=${encodeURIComponent(qrValue)}`} alt="QR-kode for medlemskort" className="mx-auto mt-5 h-60 w-60 rounded-2xl border bg-white p-3"/><div className="mt-5 flex items-center justify-center gap-2 rounded-full bg-green-50 px-4 py-2 text-sm font-semibold text-green-700"><BadgeCheck size={17}/>Aktivt medlemskap</div><p className="mt-4 text-xs leading-5 text-slate-400">Vis QR-koden ved innsjekk eller når organisasjonen ber om medlemsbevis.</p></section></main>;
}