import { useEffect, useMemo, useState } from 'react';
import { Building2, Clock3, Globe2, Loader2, Mail, MapPin, Newspaper, Phone, Share2, X } from 'lucide-react';
import { useAppI18n } from '../lib/appI18n';
import { useOrganizationModules } from '../lib/moduleEngine';
import { DEFAULT_ORGANIZATION_ID } from '../lib/organization';
import { getPublicOrganizationTranslation } from '../lib/publicOrganizationTranslations';
import { supabase } from '../lib/supabase';

type Settings = { display_name:string; short_name:string; description:string; address:string; map_url:string; phone:string; email:string; website:string; donation_number:string; donation_url:string; bank_account:string; iban:string; opening_hours:string; weekly_event:string; logo_url:string; app_icon_url:string; publish_phone:boolean; publish_email:boolean; publish_address:boolean; publish_website:boolean; publish_opening_hours:boolean; };
type News = { id:string; title:string; summary:string; content:string; image_url:string|null; published_at:string|null };
const emptySettings:Settings={display_name:'',short_name:'',description:'',address:'',map_url:'',phone:'',email:'',website:'',donation_number:'',donation_url:'',bank_account:'',iban:'',opening_hours:'',weekly_event:'',logo_url:'',app_icon_url:'',publish_phone:false,publish_email:false,publish_address:false,publish_website:false,publish_opening_hours:false};
const card='rounded-3xl border bg-white p-5 shadow-sm';

export function PublicOrganizationPage(){
  const {language,locale,direction}=useAppI18n();
  const t=(key:string)=>getPublicOrganizationTranslation(language,key);
  const {enabled,loading:modulesLoading}=useOrganizationModules(DEFAULT_ORGANIZATION_ID);
  const [settings,setSettings]=useState<Settings>(emptySettings); const [news,setNews]=useState<News[]>([]); const [selectedNews,setSelectedNews]=useState<News|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  useEffect(()=>{let cancelled=false;const load=async()=>{const client=supabase;if(!client){setLoading(false);return;}setLoading(true);setError('');const [settingsResult,newsResult]=await Promise.all([client.from('organization_settings').select('display_name,short_name,description,address,map_url,phone,email,website,donation_number,donation_url,bank_account,iban,opening_hours,weekly_event,logo_url,app_icon_url,publish_phone,publish_email,publish_address,publish_website,publish_opening_hours').eq('organization_id',DEFAULT_ORGANIZATION_ID).maybeSingle(),client.from('organization_news').select('id,title,summary,content,image_url,published_at').eq('organization_id',DEFAULT_ORGANIZATION_ID).eq('status','published').eq('visibility','public').order('published_at',{ascending:false}).limit(6)]);if(cancelled)return;const firstError=settingsResult.error||newsResult.error;if(firstError)setError(firstError.message);setSettings({...emptySettings,...(settingsResult.data||{})});const loadedNews=(newsResult.data||[]) as News[];setNews(loadedNews);setLoading(false);const requestedNews=new URLSearchParams(window.location.search).get('news');if(requestedNews)setSelectedNews(loadedNews.find(item=>item.id===requestedNews)||null);};void load();return()=>{cancelled=true;};},[language]);
  const name=settings.display_name||settings.short_name||'Yasaflow'; const logo=settings.logo_url||settings.app_icon_url; const contactVisible=Boolean((settings.publish_phone&&settings.phone)||(settings.publish_email&&settings.email)||(settings.publish_address&&settings.address)||(settings.publish_opening_hours&&settings.opening_hours)||settings.weekly_event||(settings.publish_website&&settings.website)); const phoneHref=useMemo(()=>settings.phone?`tel:${settings.phone.replace(/\s/g,'')}`:'',[settings.phone]);
  const shareNews=async(item:News)=>{const url=new URL(window.location.href);url.searchParams.set('news',item.id);try{if(navigator.share)await navigator.share({title:item.title,text:item.summary||item.content||'',url:url.toString()});else{await navigator.clipboard.writeText(url.toString());setMessage(t('public.shared'));}}catch(shareError){if((shareError as Error)?.name!=='AbortError')setError(t('public.shareFailed'));}};
  const closeNews=()=>{setSelectedNews(null);const url=new URL(window.location.href);url.searchParams.delete('news');window.history.replaceState({},'',url.toString());};
  if(loading||modulesLoading)return <div className="flex min-h-screen items-center justify-center gap-2" dir={direction}><Loader2 className="animate-spin" size={20}/><span className="text-sm opacity-60">{t('public.loading')}</span></div>;
  return <div className="min-h-screen pb-28" dir={direction} style={{background:'var(--brand-background)',color:'var(--brand-text)'}}>
    <header className="relative overflow-hidden border-b" style={{background:'var(--brand-secondary)',color:'var(--brand-secondary-text)',borderColor:'var(--brand-border)'}}><div className="absolute inset-0 bg-gradient-to-t from-black/50 via-black/20 to-transparent"/><div className="relative mx-auto flex min-h-64 max-w-4xl items-end gap-4 px-4 py-8">{logo?<img src={logo} alt="" className="h-24 w-24 rounded-3xl bg-white object-cover shadow-xl"/>:<div className="flex h-24 w-24 items-center justify-center rounded-3xl bg-white/15 backdrop-blur"><Building2 size={38}/></div>}<div className="min-w-0"><h1 className="font-serif text-3xl sm:text-4xl">{name}</h1>{settings.short_name&&settings.short_name!==name&&<p className="mt-1 text-sm opacity-75">{settings.short_name}</p>}{settings.publish_address&&settings.address&&<p className="mt-3 flex items-center gap-2 text-xs opacity-75"><MapPin size={14}/>{settings.address}</p>}</div></div></header>
    <main className="mx-auto max-w-4xl space-y-5 px-4 py-5">
      {error&&<p className="rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">{t('public.loadError')} {error}</p>}{message&&<p className="rounded-2xl bg-green-50 p-4 text-sm text-green-800">{message}</p>}
      {enabled('prayer')&&<section className="rounded-3xl border p-5 shadow-sm" style={{background:'linear-gradient(135deg,var(--brand-secondary),var(--brand-primary))',color:'var(--brand-primary-text)',borderColor:'transparent'}}><p className="text-xs font-semibold uppercase tracking-[.16em] opacity-70">{t('public.prayerLabel')}</p><h2 className="mt-2 text-2xl font-semibold">{t('public.prayerTitle')}</h2><p className="mt-2 text-sm opacity-80">{t('public.prayerDescription')}</p></section>}
      {settings.description&&<section className={card}><h2 className="font-serif text-xl">{t('public.about')}</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 opacity-70">{settings.description}</p></section>}
      {enabled('news',true)&&<section className={card}><div className="flex items-center gap-2"><Newspaper size={20}/><h2 className="font-serif text-xl">{t('public.news')}</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{news.length===0?<p className="rounded-2xl border p-5 text-sm opacity-50 sm:col-span-2">{t('public.noNews')}</p>:news.map(item=><article key={item.id} className="overflow-hidden rounded-2xl border">{item.image_url&&<button type="button" onClick={()=>setSelectedNews(item)} className="block w-full bg-black/5"><img src={item.image_url} alt="" className="h-auto max-h-72 w-full object-contain"/></button>}<div className="p-4"><p className="text-[11px] opacity-45">{item.published_at?`${t('public.published')} ${new Date(item.published_at).toLocaleDateString(locale)}`:t('public.published')}</p><h3 className="mt-1 font-serif text-lg">{item.title}</h3><p className="mt-2 line-clamp-3 text-sm opacity-65">{item.summary||item.content||t('public.noDescription')}</p><button type="button" onClick={()=>setSelectedNews(item)} className="mt-3 text-sm font-semibold" style={{color:'var(--brand-primary)'}}>{t('public.readMore')}</button></div></article>)}</div></section>}
      {contactVisible&&<section className={card}><h2 className="font-serif text-xl">{t('public.contact')}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{settings.publish_phone&&settings.phone&&<a href={phoneHref} className="flex items-center gap-3 rounded-2xl border p-4"><Phone size={18}/><span className="text-sm font-semibold">{settings.phone}</span></a>}{settings.publish_email&&settings.email&&<a href={`mailto:${settings.email}`} className="flex items-center gap-3 rounded-2xl border p-4"><Mail size={18}/><span className="text-sm font-semibold">{settings.email}</span></a>}{settings.publish_address&&settings.address&&<a href={settings.map_url||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(settings.address)}`} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-2xl border p-4"><MapPin size={18}/><span className="text-sm font-semibold">{settings.address}</span></a>}{settings.publish_opening_hours&&settings.opening_hours&&<div className="flex items-center gap-3 rounded-2xl border p-4"><Clock3 size={18}/><span className="text-sm font-semibold">{settings.opening_hours}</span></div>}{settings.publish_website&&settings.website&&<a href={settings.website} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-2xl border p-4"><Globe2 size={18}/><span className="text-sm font-semibold">{settings.website}</span></a>}</div></section>}
    </main>
    {selectedNews&&<div className="fixed inset-0 z-[150] flex items-end justify-center bg-black/45 sm:items-center sm:p-4"><article className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white sm:rounded-3xl">{selectedNews.image_url&&<img src={selectedNews.image_url} alt="" className="mx-auto h-auto max-h-[70vh] w-full object-contain"/>}<div className="p-5"><div className="flex items-start justify-between gap-4"><h2 className="font-serif text-3xl">{selectedNews.title}</h2><button onClick={closeNews} className="rounded-full bg-black/5 p-2"><X size={18}/></button></div><p className="mt-4 whitespace-pre-wrap text-sm leading-7 opacity-75">{selectedNews.content||selectedNews.summary}</p><button onClick={()=>void shareNews(selectedNews)} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl border py-3 text-sm font-semibold"><Share2 size={16}/>{t('public.share')}</button></div></article></div>}
  </div>;
}
