import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { BarChart3, Camera, CameraOff, CheckCircle2, ClipboardList, CloudUpload, Download, Loader2, Mail, QrCode, RefreshCw, Send, Signal, SignalZero, UserCheck, Users, XCircle } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { ArrangementProTools } from './ArrangementProTools';
import { ActivityBadgePrintPanel } from './ActivityBadgePrintPanel';

type Activity={id:string;title:string;activity_date:string};
type Attendance={checkin_id:string;membership_id:string|null;member_number:string|null;full_name:string;email:string|null;checked_in_at:string;source:string;attendee_count:number};
type Registration={registration_id:string;full_name:string;email:string;phone:string|null;attendees:number;status:string;created_at:string;membership_id:string|null;member_number:string|null;checked_in:boolean;checked_in_at:string|null;payment_confirmed:boolean;confirmation_email_sent_at:string|null;ticket_token:string;checked_in_attendees:number;remaining_attendees:number};
type ScanResult={kind:'success'|'duplicate'|'error';message:string};
type Audience='confirmed'|'waitlist'|'unpaid'|'not_checked_in';
type DetectorResult={rawValue?:string};
type Detector={detect:(source:CanvasImageSource)=>Promise<DetectorResult[]>};
type DetectorConstructor={new(options:{formats:string[]}):Detector};
type GroupCheckin={ticketToken:string;fullName:string;totalAttendees:number;checkedInAttendees:number;remainingAttendees:number;offline?:boolean};
type OfflineCheckin={id:string;kind:'ticket'|'member';token:string;attendeeCount:number;fullName:string;createdAt:string;attempts:number;lastError?:string};

const csvCell=(value:unknown)=>`"${String(value??'').replace(/"/g,'""')}"`;
const uuidPattern=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const makeId=()=>typeof crypto!=='undefined'&&'randomUUID'in crypto?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;

export function ActivityAttendancePanel({organizationId,activity,onClose}:{organizationId:string;activity:Activity;onClose:()=>void}){
  const [attendance,setAttendance]=useState<Attendance[]>([]);
  const [registrations,setRegistrations]=useState<Registration[]>([]);
  const [loading,setLoading]=useState(true);
  const [code,setCode]=useState('');
  const [checking,setChecking]=useState(false);
  const [result,setResult]=useState<ScanResult|null>(null);
  const [pendingGroup,setPendingGroup]=useState<GroupCheckin|null>(null);
  const [cameraOn,setCameraOn]=useState(false);
  const [cameraError,setCameraError]=useState('');
  const [online,setOnline]=useState(()=>navigator.onLine);
  const [lastScanAt,setLastScanAt]=useState<string|null>(null);
  const [offlineQueue,setOfflineQueue]=useState<OfflineCheckin[]>([]);
  const [syncing,setSyncing]=useState(false);
  const [lastSyncedAt,setLastSyncedAt]=useState<string|null>(null);
  const [resendingId,setResendingId]=useState('');
  const [promotingId,setPromotingId]=useState('');
  const [audience,setAudience]=useState<Audience>('confirmed');
  const [broadcastSubject,setBroadcastSubject]=useState('');
  const [broadcastMessage,setBroadcastMessage]=useState('');
  const [sendingBroadcast,setSendingBroadcast]=useState(false);
  const videoRef=useRef<HTMLVideoElement|null>(null);
  const streamRef=useRef<MediaStream|null>(null);
  const timerRef=useRef<number|null>(null);
  const busyRef=useRef(false);
  const syncRef=useRef(false);
  const lastValueRef=useRef('');
  const lastValueAtRef=useRef(0);
  const queueKey=`yasaflow-offline-checkins:${organizationId}:${activity.id}`;

  const saveQueue=(items:OfflineCheckin[])=>{setOfflineQueue(items);try{localStorage.setItem(queueKey,JSON.stringify(items));}catch{setResult({kind:'error',message:'Enheten har ikke plass til å lagre flere offline-innsjekkinger.'});}};
  const feedback=(kind:ScanResult['kind'])=>{if('vibrate'in navigator)navigator.vibrate(kind==='success'?[80]:kind==='duplicate'?[60,50,60]:[160,70,160]);try{const AudioContextClass=window.AudioContext||(window as unknown as {webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AudioContextClass)return;const context=new AudioContextClass();const oscillator=context.createOscillator();const gain=context.createGain();oscillator.connect(gain);gain.connect(context.destination);oscillator.frequency.value=kind==='success'?880:kind==='duplicate'?520:220;gain.gain.value=.08;oscillator.start();oscillator.stop(context.currentTime+(kind==='success'?.09:.16));oscillator.onended=()=>void context.close();}catch{}};
  const stopCamera=()=>{if(timerRef.current)window.clearInterval(timerRef.current);timerRef.current=null;streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;setCameraOn(false);};
  const loadData=async(silent=false)=>{if(!supabase||!navigator.onLine)return;if(!silent)setLoading(true);const[a,r]=await Promise.all([supabase.rpc('get_activity_attendance',{p_activity_id:activity.id}),supabase.rpc('get_activity_registration_overview',{p_activity_id:activity.id})]);if(a.error)setResult({kind:'error',message:a.error.message});else setAttendance((a.data||[])as Attendance[]);if(r.error)setResult({kind:'error',message:r.error.message});else setRegistrations((r.data||[])as Registration[]);if(!silent)setLoading(false);};

  const enqueueOffline=(item:Omit<OfflineCheckin,'id'|'createdAt'|'attempts'>)=>{const next=[...offlineQueue,{...item,id:makeId(),createdAt:new Date().toISOString(),attempts:0}];saveQueue(next);const message=`${item.fullName}: ${item.attendeeCount} innsjekking${item.attendeeCount===1?'':'er'} lagret offline.`;setResult({kind:'success',message});setLastScanAt(new Date().toISOString());setCode('');feedback('success');lastValueRef.current='';};

  const syncOfflineQueue=async(manual=false)=>{if(!supabase||!navigator.onLine||syncRef.current||offlineQueue.length===0)return;syncRef.current=true;setSyncing(true);let sent=0;let conflicts=0;const remaining:OfflineCheckin[]=[];for(const item of offlineQueue){try{if(item.kind==='ticket'){const{data,error}=await supabase.rpc('check_in_registration_group_by_ticket',{p_organization_id:organizationId,p_activity_id:activity.id,p_ticket_token:item.token,p_attendee_count:item.attendeeCount});if(error)throw error;const payload=data as{status?:string};if(payload.status==='already_checked_in')conflicts++;else sent++;}else{const{data,error}=await supabase.rpc('check_in_member_by_card',{p_organization_id:organizationId,p_activity_id:activity.id,p_card_token:item.token});if(error)throw error;const payload=data as{status?:string};if(payload.status==='already_checked_in')conflicts++;else sent++;}}catch(error){const message=error instanceof Error?error.message:String(error);if(message.includes('ticket_not_found')||message.includes('not_authorized')||message.includes('invalid_attendee_count'))conflicts++;else remaining.push({...item,attempts:item.attempts+1,lastError:message});}}
    saveQueue(remaining);const now=new Date().toISOString();setLastSyncedAt(now);localStorage.setItem(`${queueKey}:last-sync`,now);await loadData(true);if(manual||sent||conflicts)setResult({kind:remaining.length?'error':conflicts?'duplicate':'success',message:remaining.length?`${sent} synkronisert. ${remaining.length} venter fortsatt.`:conflicts?`${sent} synkronisert. ${conflicts} var allerede registrert eller ugyldige.`:`${sent} offline-innsjekking${sent===1?'':'er'} synkronisert.`});setSyncing(false);syncRef.current=false;};

  useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem(queueKey)||'[]')as OfflineCheckin[];setOfflineQueue(Array.isArray(stored)?stored:[]);setLastSyncedAt(localStorage.getItem(`${queueKey}:last-sync`));}catch{setOfflineQueue([]);}void loadData();const setConnected=()=>{setOnline(true);window.setTimeout(()=>void syncOfflineQueue(),300);};const setDisconnected=()=>setOnline(false);window.addEventListener('online',setConnected);window.addEventListener('offline',setDisconnected);const channel=supabase?.channel(`activity-checkin-${activity.id}`).on('postgres_changes',{event:'*',schema:'public',table:'activity_checkins',filter:`activity_id=eq.${activity.id}`},()=>void loadData(true)).on('postgres_changes',{event:'*',schema:'public',table:'activity_registrations',filter:`activity_id=eq.${activity.id}`},()=>void loadData(true)).subscribe();return()=>{stopCamera();window.removeEventListener('online',setConnected);window.removeEventListener('offline',setDisconnected);if(channel&&supabase)void supabase.removeChannel(channel);};},[activity.id,organizationId]);
  useEffect(()=>{if(online&&offlineQueue.length&&!syncRef.current)void syncOfflineQueue();},[online,offlineQueue.length]);

  const completeGroupCheckin=async(group:GroupCheckin,count:number)=>{if(group.offline){enqueueOffline({kind:'ticket',token:group.ticketToken,attendeeCount:count,fullName:group.fullName});setPendingGroup(null);return;}if(!supabase||busyRef.current)return;busyRef.current=true;setChecking(true);setResult(null);try{const{data,error}=await supabase.rpc('check_in_registration_group_by_ticket',{p_organization_id:organizationId,p_activity_id:activity.id,p_ticket_token:group.ticketToken,p_attendee_count:count});if(error)throw error;const payload=data as{status?:string;full_name?:string;added_attendees?:number;remaining_attendees?:number};const added=payload.added_attendees??count;const remaining=payload.remaining_attendees??0;const next:ScanResult=payload.status==='already_checked_in'?{kind:'duplicate',message:`${payload.full_name||group.fullName}: hele gruppen er allerede sjekket inn.`}:{kind:'success',message:`${added} deltaker${added===1?'':'e'} sjekket inn for ${payload.full_name||group.fullName}.${remaining?` ${remaining} gjenstår.`:' Hele gruppen er inne.'}`};setPendingGroup(null);setResult(next);feedback(next.kind);setLastScanAt(new Date().toISOString());setCode('');await loadData(true);}catch(error){const message=error instanceof Error?error.message:String(error);setResult({kind:'error',message:message.includes('invalid_attendee_count')?'Velg minst én deltaker.':message.includes('ticket_not_found')?'Billetten er ugyldig, avmeldt eller står på venteliste.':message.includes('not_authorized')?'Du har ikke tilgang til innsjekking.':message});feedback('error');await loadData(true);}finally{setChecking(false);busyRef.current=false;lastValueRef.current='';}};

  const checkIn=async(raw:string)=>{if(!supabase||busyRef.current||pendingGroup)return;const value=raw.trim();if(!value)return;const now=Date.now();if(value===lastValueRef.current&&now-lastValueAtRef.current<2500)return;lastValueRef.current=value;lastValueAtRef.current=now;const ticketPrefix=`yasaflow-ticket:${organizationId}:${activity.id}:`;const memberPrefix=`yasaflow-member:${organizationId}:`;try{if(!navigator.onLine){if(value.startsWith(ticketPrefix)){const token=value.slice(ticketPrefix.length);if(!uuidPattern.test(token))throw new Error('Ugyldig arrangementsbillett.');const row=registrations.find(registration=>registration.ticket_token===token&&registration.status==='confirmed');if(!row)throw new Error('Billetten finnes ikke i den lokale arrangementslisten. Koble til internett én gang for å oppdatere listen.');const queued=offlineQueue.filter(item=>item.kind==='ticket'&&item.token===token).reduce((sum,item)=>sum+item.attendeeCount,0);const checked=row.checked_in_attendees??0;const remaining=Math.max(0,row.attendees-checked-queued);if(!remaining){setResult({kind:'duplicate',message:`${row.full_name}: hele gruppen er allerede registrert eller ligger i offline-køen.`});feedback('duplicate');lastValueRef.current='';return;}const group:GroupCheckin={ticketToken:token,fullName:row.full_name,totalAttendees:row.attendees,checkedInAttendees:checked+queued,remainingAttendees:remaining,offline:true};if(row.attendees>1){setPendingGroup(group);setCode('');}else enqueueOffline({kind:'ticket',token,attendeeCount:1,fullName:row.full_name});}else{const token=value.startsWith(memberPrefix)?value.slice(memberPrefix.length):value;if(!uuidPattern.test(token))throw new Error('QR-koden tilhører ikke denne organisasjonen.');if(offlineQueue.some(item=>item.kind==='member'&&item.token===token)){setResult({kind:'duplicate',message:'Medlemmet ligger allerede i offline-køen.'});feedback('duplicate');lastValueRef.current='';return;}enqueueOffline({kind:'member',token,attendeeCount:1,fullName:'Medlem'});}return;}
      busyRef.current=true;setChecking(true);setResult(null);if(value.startsWith(ticketPrefix)){const token=value.slice(ticketPrefix.length);if(!uuidPattern.test(token))throw new Error('Ugyldig arrangementsbillett.');const{data,error}=await supabase.rpc('get_registration_ticket_checkin_status',{p_organization_id:organizationId,p_activity_id:activity.id,p_ticket_token:token});if(error)throw error;const payload=data as{full_name?:string;total_attendees?:number;checked_in_attendees?:number;remaining_attendees?:number};const group:GroupCheckin={ticketToken:token,fullName:payload.full_name||'Bestillingen',totalAttendees:payload.total_attendees??1,checkedInAttendees:payload.checked_in_attendees??0,remainingAttendees:payload.remaining_attendees??0};if(group.remainingAttendees<=0){setResult({kind:'duplicate',message:`${group.fullName}: hele gruppen er allerede sjekket inn.`});feedback('duplicate');}else if(group.totalAttendees>1){setPendingGroup(group);setCode('');}else{busyRef.current=false;setChecking(false);await completeGroupCheckin(group,1);return;}}else{const token=value.startsWith(memberPrefix)?value.slice(memberPrefix.length):value;if(!uuidPattern.test(token))throw new Error('QR-koden tilhører ikke dette arrangementet eller organisasjonen.');const{data,error}=await supabase.rpc('check_in_member_by_card',{p_organization_id:organizationId,p_activity_id:activity.id,p_card_token:token});if(error)throw error;const payload=data as{status?:string};const next:ScanResult=payload.status==='already_checked_in'?{kind:'duplicate',message:'Medlemmet er allerede sjekket inn.'}:{kind:'success',message:'Medlemmet er sjekket inn.'};setResult(next);feedback(next.kind);setLastScanAt(new Date().toISOString());setCode('');await loadData(true);}}catch(error){const message=error instanceof Error?error.message:String(error);setResult({kind:'error',message:message.includes('ticket_not_found')?'Billetten er ugyldig, avmeldt eller står på venteliste.':message.includes('not_authorized')?'Du har ikke tilgang til innsjekking.':message});feedback('error');lastValueRef.current='';}finally{setChecking(false);busyRef.current=false;}};

  const startCamera=async()=>{setCameraError('');const DetectorClass=(window as unknown as{BarcodeDetector?:DetectorConstructor}).BarcodeDetector;if(!DetectorClass){setCameraError('Kameraskanning støttes ikke i denne nettleseren. Bruk Chrome på mobil eller lim inn koden.');return;}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}}});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play();}setCameraOn(true);const detector=new DetectorClass({formats:['qr_code']});timerRef.current=window.setInterval(async()=>{const video=videoRef.current;if(!video||video.readyState<2||busyRef.current||pendingGroup)return;try{const found=await detector.detect(video);const value=found[0]?.rawValue;if(value)await checkIn(value);}catch{}},250);}catch{setCameraError('Kamera kunne ikke åpnes. Kontroller kameratillatelsen.');stopCamera();}};
  const submit=(event:FormEvent)=>{event.preventDefault();void checkIn(code);};
  const resendTicket=async(row:Registration)=>{if(!supabase||resendingId)return;setResendingId(row.registration_id);setResult(null);try{const{data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('Du må være innlogget for å sende billetten på nytt.');const response=await fetch('/api/send-activity-ticket',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({registrationId:row.registration_id,ticketToken:row.ticket_token,force:true})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error||'Billetten kunne ikke sendes.');setResult({kind:'success',message:`Billetten er sendt på nytt til ${row.email}.`});await loadData(true);}catch(error){setResult({kind:'error',message:error instanceof Error?error.message:String(error)});}finally{setResendingId('');}};
  const promoteWaitlist=async(row:Registration)=>{if(!supabase||promotingId)return;if(!window.confirm(`Bekreft plass for ${row.full_name}? En aktiv QR-billett sendes automatisk.`))return;setPromotingId(row.registration_id);setResult(null);try{const{data,error}=await supabase.rpc('promote_activity_waitlist_registration',{p_registration_id:row.registration_id});if(error)throw error;const payload=data as{full_name?:string;email?:string};setResult({kind:'success',message:`${payload.full_name||row.full_name} er flyttet fra venteliste. QR-billett sendes til ${payload.email||row.email}.`});await loadData(true);}catch(error){const message=error instanceof Error?error.message:String(error);setResult({kind:'error',message:message.includes('capacity_exceeded')?'Det er ikke nok ledige plasser til denne påmeldingen.':message.includes('registration_not_waitlisted')?'Påmeldingen står ikke lenger på venteliste.':message.includes('not_authorized')?'Du har ikke tilgang til å endre ventelisten.':message});}finally{setPromotingId('');}};
  const recipientCount=useMemo(()=>audience==='confirmed'?registrations.filter(r=>r.status==='confirmed').length:audience==='waitlist'?registrations.filter(r=>r.status==='waitlist').length:audience==='unpaid'?registrations.filter(r=>r.status==='confirmed'&&!r.payment_confirmed).length:registrations.filter(r=>r.status==='confirmed'&&!r.checked_in).length,[audience,registrations]);
  const sendBroadcast=async(event:FormEvent)=>{event.preventDefault();if(!supabase||sendingBroadcast||!recipientCount)return;if(!window.confirm(`Send e-post til ${recipientCount} mottaker(e)?`))return;setSendingBroadcast(true);setResult(null);try{const{data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('Du må være innlogget for å sende e-post.');const response=await fetch('/api/send-activity-broadcast',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({activityId:activity.id,organizationId,audience,subject:broadcastSubject,message:broadcastMessage})});const payload=await response.json().catch(()=>({}));if(!response.ok&&response.status!==207)throw new Error(payload?.error||'E-posten kunne ikke sendes.');setResult({kind:payload.failed?'duplicate':'success',message:payload.failed?`${payload.sent} sendt, ${payload.failed} mislyktes.`:`E-posten ble sendt til ${payload.sent} mottaker(e).`});if(!payload.failed){setBroadcastSubject('');setBroadcastMessage('');}}catch(error){setResult({kind:'error',message:error instanceof Error?error.message:String(error)});}finally{setSendingBroadcast(false);}};
  const downloadCsv=(rows:unknown[][],name:string)=>{const content='\uFEFF'+rows.map(row=>row.map(csvCell).join(';')).join('\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`${name.toLowerCase().replace(/[^a-z0-9æøå]+/gi,'-')}.csv`;link.click();URL.revokeObjectURL(url);};
  const exportRegistrations=()=>downloadCsv([['Navn','E-post','Telefon','Antall','Sjekket inn','Gjenstår','Status','Betaling bekreftet'],...registrations.map(row=>[row.full_name,row.email,row.phone,row.attendees,row.checked_in_attendees??0,row.remaining_attendees??row.attendees,row.status,row.payment_confirmed?'Ja':'Nei'])],`pameldinger-${activity.title}`);
  const exportAttendance=()=>downloadCsv([['Navn','Antall','Medlemsnummer','E-post','Innsjekket','Metode'],...attendance.map(row=>[row.full_name,row.attendee_count??1,row.member_number,row.email,new Date(row.checked_in_at).toLocaleString('nb-NO'),row.source])],`oppmote-${activity.title}`);
  const stats=useMemo(()=>{const confirmed=registrations.filter(row=>row.status==='confirmed');const registered=confirmed.reduce((sum,row)=>sum+row.attendees,0);const waitlist=registrations.filter(row=>row.status==='waitlist').reduce((sum,row)=>sum+row.attendees,0);const paid=confirmed.filter(row=>row.payment_confirmed).reduce((sum,row)=>sum+row.attendees,0);const unpaid=Math.max(0,registered-paid);const checkedIn=attendance.reduce((sum,row)=>sum+(row.attendee_count||1),0);const queued=offlineQueue.reduce((sum,row)=>sum+row.attendeeCount,0);const attendanceRate=registered?Math.min(100,Math.round(((checkedIn+queued)/registered)*100)):0;return{registered,waitlist,paid,unpaid,checkedIn,queued,attendanceRate};},[registrations,attendance,offlineQueue]);
  const quickCounts=pendingGroup?Array.from(new Set([1,2,3].filter(value=>value<=pendingGroup.remainingAttendees))):[];

  return <div className="fixed inset-0 z-[150] overflow-y-auto bg-black/55 p-0 sm:p-4"><div className="mx-auto min-h-full w-full max-w-5xl bg-white p-5 sm:min-h-0 sm:rounded-3xl">
    <div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-widest opacity-45">Arrangement Pro</p><h3 className="font-serif text-2xl">QR Check-in 2.0</h3><p className="mt-1 text-sm opacity-60">{activity.title} · {activity.activity_date}</p></div><button onClick={()=>{stopCamera();onClose();}} className="rounded-full bg-black/5 p-2" aria-label="Lukk"><XCircle size={20}/></button></div>
    <div className={`mt-3 rounded-xl px-3 py-2 text-xs ${online?'bg-green-50 text-green-700':'bg-amber-50 text-amber-800'}`}><div className="flex items-center gap-2">{online?<Signal size={15}/>:<SignalZero size={15}/>}<span>{online?'Tilkoblet – live synkronisering aktiv':'Offline – skanninger lagres trygt på enheten'}</span>{lastScanAt&&<span className="ml-auto opacity-70">Sist skannet {new Date(lastScanAt).toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</span>}</div>{(offlineQueue.length>0||lastSyncedAt)&&<div className="mt-2 flex items-center gap-2 border-t border-current/10 pt-2"><CloudUpload size={14}/><span>{offlineQueue.length} ventende · {stats.queued} deltaker{stats.queued===1?'':'e'}</span>{lastSyncedAt&&<span className="opacity-60">· Sist synk. {new Date(lastSyncedAt).toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit'})}</span>}<button type="button" disabled={!online||syncing||!offlineQueue.length} onClick={()=>void syncOfflineQueue(true)} className="ml-auto flex items-center gap-1 rounded-lg border border-current/20 px-2 py-1 font-semibold disabled:opacity-40">{syncing?<Loader2 size={13} className="animate-spin"/>:<RefreshCw size={13}/>}Synkroniser nå</button></div>}</div>
    <section className="mt-4 rounded-2xl border p-4"><div className="flex items-center gap-2"><BarChart3 size={18}/><h4 className="font-semibold">Live oversikt</h4></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7">{[['Påmeldte',stats.registered],['Venteliste',stats.waitlist],['Møtt',stats.checkedIn],['Offline',stats.queued],['Betalt',stats.paid],['Ikke betalt',stats.unpaid],['Oppmøte',`${stats.attendanceRate}%`]].map(([label,value])=><div key={String(label)} className="rounded-2xl bg-black/[0.03] p-3 text-center"><p className="text-xl font-semibold">{value}</p><p className="text-[11px] opacity-50">{label}</p></div>)}</div></section>
    {result&&<div className={`mt-4 flex gap-2 rounded-xl p-4 text-sm ${result.kind==='success'?'bg-green-50 text-green-800':result.kind==='duplicate'?'bg-amber-50 text-amber-800':'bg-red-50 text-red-800'}`}>{result.kind==='success'?<CheckCircle2 size={20}/>:<XCircle size={20}/>}<p className="font-semibold">{result.message}</p></div>}
    <section className="mt-5 rounded-2xl border p-4"><div className="flex items-center gap-2"><QrCode size={18}/><div><h4 className="font-semibold">Kontinuerlig QR-skanning</h4><p className="text-xs opacity-55">Kameraet fungerer også offline og fortsetter etter hver skanning.</p></div></div><div className="relative mt-4 overflow-hidden rounded-2xl bg-black"><video ref={videoRef} playsInline muted className={`aspect-video w-full object-cover ${cameraOn?'block':'hidden'}`}/>{cameraOn&&<div className="pointer-events-none absolute inset-0 flex items-center justify-center"><div className="h-44 w-44 rounded-2xl border-2 border-white/80 shadow-[0_0_0_999px_rgba(0,0,0,.28)]"/></div>}{!cameraOn&&<div className="flex aspect-video items-center justify-center text-white/55"><Camera size={42}/></div>}</div><button onClick={cameraOn?stopCamera:()=>void startCamera()} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border py-3 text-sm font-semibold">{cameraOn?<><CameraOff size={17}/>Stopp kamera</>:<><Camera size={17}/>Start rask skanning</>}</button>{cameraError&&<p className="mt-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">{cameraError}</p>}<form onSubmit={submit} className="mt-4"><input autoFocus value={code} onChange={event=>setCode(event.target.value)} className="w-full rounded-xl border p-3 text-sm" placeholder="Skann med ekstern leser eller lim inn QR-token"/><button disabled={checking||!code.trim()||!!pendingGroup} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl py-3 text-sm font-semibold disabled:opacity-50" style={{background:'var(--brand-primary)',color:'var(--brand-primary-text)'}}>{checking&&<Loader2 size={16} className="animate-spin"/>}{online?'Registrer innsjekk':'Lagre offline'}</button></form></section>
    <ActivityBadgePrintPanel activityId={activity.id} organizationId={organizationId} registrations={registrations} onError={message=>setResult({kind:'error',message})}/>
    <ArrangementProTools activity={activity} organizationId={organizationId}/>
    <section className="mt-5 rounded-2xl border p-4"><div className="flex items-center gap-2"><Mail size={18}/><h4 className="font-semibold">Send beskjed</h4></div><form onSubmit={sendBroadcast} className="mt-4 space-y-3"><select value={audience} onChange={e=>setAudience(e.target.value as Audience)} className="w-full rounded-xl border p-3 text-sm"><option value="confirmed">Alle bekreftede</option><option value="waitlist">Venteliste</option><option value="unpaid">Ikke betalt</option><option value="not_checked_in">Ikke møtt</option></select><input required maxLength={160} value={broadcastSubject} onChange={e=>setBroadcastSubject(e.target.value)} className="w-full rounded-xl border p-3 text-sm" placeholder="Emne"/><textarea required maxLength={8000} rows={4} value={broadcastMessage} onChange={e=>setBroadcastMessage(e.target.value)} className="w-full rounded-xl border p-3 text-sm" placeholder="Melding"/><button disabled={sendingBroadcast||!recipientCount||!online} className="flex w-full items-center justify-center gap-2 rounded-xl py-3 text-sm font-semibold disabled:opacity-45" style={{background:'var(--brand-primary)',color:'var(--brand-primary-text)'}}>{sendingBroadcast?<Loader2 size={16} className="animate-spin"/>:<Send size={16}/>}Send til {recipientCount}</button></form></section>
    <div className="mt-4 grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><ClipboardList size={18}/><h4 className="font-semibold">Påmeldinger</h4></div><button onClick={exportRegistrations} className="flex items-center gap-1 rounded-lg border px-2 py-2 text-xs"><Download size={14}/>CSV</button></div>{loading?<div className="flex justify-center p-8"><Loader2 className="animate-spin"/></div>:<div className="mt-4 max-h-[480px] space-y-2 overflow-y-auto">{registrations.map(row=><article key={row.registration_id} className="rounded-xl border p-3"><p className="text-sm font-semibold">{row.full_name}</p><p className="text-xs opacity-55">{row.email} · {row.attendees} påmeldt · {row.checked_in_attendees??0} inne · {row.remaining_attendees??row.attendees} gjenstår</p>{row.status==='waitlist'&&<button type="button" disabled={promotingId===row.registration_id||!online} onClick={()=>void promoteWaitlist(row)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl py-2.5 text-xs font-semibold text-white disabled:opacity-45" style={{background:'var(--brand-primary)'}}>{promotingId===row.registration_id?<Loader2 size={15} className="animate-spin"/>:<UserCheck size={15}/>}Bekreft plass</button>}<button type="button" disabled={resendingId===row.registration_id||row.status==='cancelled'||!row.ticket_token||!online} onClick={()=>void resendTicket(row)} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl border py-2.5 text-xs font-semibold disabled:opacity-45"><Mail size={15}/><RefreshCw size={13}/>Send billett på nytt</button></article>)}</div>}</section><section className="rounded-2xl border p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Users size={18}/><h4 className="font-semibold">Oppmøte</h4></div><button onClick={exportAttendance} className="flex items-center gap-1 rounded-lg border px-2 py-2 text-xs"><Download size={14}/>CSV</button></div><div className="mt-4 max-h-[480px] space-y-2 overflow-y-auto">{offlineQueue.map(row=><article key={row.id} className="rounded-xl border border-amber-200 bg-amber-50 p-3"><p className="text-sm font-semibold">{row.fullName}</p><p className="text-xs text-amber-800">{row.attendeeCount} venter på synkronisering · {new Date(row.createdAt).toLocaleString('nb-NO')}</p></article>)}{attendance.map(row=><article key={row.checkin_id} className="rounded-xl border p-3"><p className="text-sm font-semibold">{row.full_name}</p><p className="text-xs opacity-55">{row.attendee_count||1} deltaker{(row.attendee_count||1)===1?'':'e'} · {row.email||'Ingen e-post'} · {new Date(row.checked_in_at).toLocaleString('nb-NO')}</p></article>)}</div></section></div>
  </div>
  {pendingGroup&&<div className="fixed inset-0 z-[170] flex items-end justify-center bg-black/60 p-0 sm:items-center sm:p-4"><div className="w-full max-w-md rounded-t-3xl bg-white p-5 shadow-2xl sm:rounded-3xl"><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-widest opacity-45">{pendingGroup.offline?'Offline gruppeinnsjekking':'Gruppeinnsjekking'}</p><h4 className="mt-1 text-xl font-semibold">{pendingGroup.fullName}</h4></div><button type="button" onClick={()=>{setPendingGroup(null);lastValueRef.current='';}} className="rounded-full bg-black/5 p-2" aria-label="Avbryt"><XCircle size={20}/></button></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl bg-black/[0.03] p-3"><p className="text-2xl font-semibold">{pendingGroup.totalAttendees}</p><p className="text-[11px] opacity-50">Totalt</p></div><div className="rounded-2xl bg-green-50 p-3 text-green-800"><p className="text-2xl font-semibold">{pendingGroup.checkedInAttendees}</p><p className="text-[11px]">Registrert</p></div><div className="rounded-2xl bg-amber-50 p-3 text-amber-800"><p className="text-2xl font-semibold">{pendingGroup.remainingAttendees}</p><p className="text-[11px]">Gjenstår</p></div></div>{pendingGroup.offline&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">Valget lagres på denne enheten og synkroniseres automatisk når nettet kommer tilbake.</p>}<p className="mt-5 text-sm font-medium">Hvor mange møter nå?</p><div className="mt-3 grid grid-cols-3 gap-2">{quickCounts.map(count=><button key={count} type="button" disabled={checking} onClick={()=>void completeGroupCheckin(pendingGroup,count)} className="rounded-2xl border py-4 text-lg font-semibold disabled:opacity-45">+{count}</button>)}</div><button type="button" disabled={checking} onClick={()=>void completeGroupCheckin(pendingGroup,pendingGroup.remainingAttendees)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-2xl py-4 font-semibold disabled:opacity-45" style={{background:'var(--brand-primary)',color:'var(--brand-primary-text)'}}>{checking?<Loader2 size={18} className="animate-spin"/>:<CheckCircle2 size={18}/>}Sjekk inn alle {pendingGroup.remainingAttendees}</button><button type="button" disabled={checking} onClick={()=>{setPendingGroup(null);lastValueRef.current='';}} className="mt-2 w-full rounded-2xl border py-3 text-sm font-semibold disabled:opacity-45">Avbryt</button></div></div>}
  </div>;
}
